# proto-file: proto/templated_plugin.proto
# proto-message: TemplatedPlugin

###############
# PLUGIN INFO #
###############

info: {
  type: VULN_DETECTION
  name: "Drupal_CVE_2026_10768"
  author: "dyeddala"
  version: "1.3"
}

finding: {
  main_id: {
    publisher: "GOOGLE"
    value: "CVE-2026-10768"
  }
  severity: HIGH
  title: "Drupal LocalGov Workflows - Missing Authorization (Forceful Browsing)"
  description: "Missing Authorization vulnerability in Drupal LocalGov Workflows allows Forceful Browsing without required permissions. This issue affects LocalGov Workflows versions prior to 1.6.0. Note: In this CVE, \"Forceful Browsing\" just means missing authentication for a URL, specifically a Service Contacts page. "
  recommendation: "Update the Drupal LocalGov Workflows module to version 1.6.0 or later."
  related_id: {
    publisher: "CVE"
    value: "CVE-2026-10768"
  }
}

config: {}

###########
# ACTIONS #
###########

actions: {
  name: "fingerprint_localgov_workflows"
  http_request: {
    method: GET
    uri: "/core/misc/drupal.js"
    response: {
      http_status: 200
      expect_any: {
        conditions: [
          { body: {} contains: "window.Drupal" }
        ]
      }
    }
  }
}

actions: {
  name: "check_forceful_browsing_access"
  http_request: {
    method: GET
    uri: "/admin/content/localgov-service-contact/content-by-owner"
    response: {
      http_status: 200
      expect_all: {
        conditions: [
          {
            body: {}
            contains: "Content by owner"
          }
        ]
      }
    }
  }
}

#############
# WORKFLOWS #
#############

workflows: {
  actions: [
    "fingerprint_localgov_workflows",
    "check_forceful_browsing_access"
  ]
}
