# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "RClone_CVE_2026_41179"
}

########
# TESTS #
########

tests: {
  name: "whenVulnerable_returnsTrue"
  expect_vulnerability: true
  mock_http_server: {
    mock_responses: [
      {
        uri: "/rc/noop"
        status: 200
        headers: [
          { name: "Content-Type" value: "application/json" }
        ]
        body_content: "{}"
      },
      {
        uri: "/operations/fsinfo"
        status: 200
        headers: [
          { name: "Content-Type" value: "application/json" }
        ]
        body_content: "{\"Features\":{\"CanHaveEmptyDirectories\":true}}"
      }
    ]
  }
}

tests: {
  name: "whenNotVulnerable_returnsFalse"
  expect_vulnerability: false
  mock_http_server: {
    mock_responses: [
      {
        uri: "/rc/noop"
        status: 200
        headers: [
          { name: "Content-Type" value: "application/json" }
        ]
        body_content: "{}"
      },
      {
        uri: "/operations/fsinfo"
        status: 400
        headers: [
          { name: "Content-Type" value: "application/json" }
        ]
        body_content: "{\"error\":\"operation failed\"}"
      }
    ]
  }
}

tests: {
  name: "whenNotRclone_returnsFalse"
  expect_vulnerability: false
  mock_http_server: {
    mock_responses: [
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 404
        body_content: "404 Not Found"
      }
    ]
  }
}
