// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: action_http.proto

package templated_plugin_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpAction_HttpMethod int32

const (
	HttpAction_METHOD_UNSPECIFIED HttpAction_HttpMethod = 0
	HttpAction_GET                HttpAction_HttpMethod = 1
	HttpAction_POST               HttpAction_HttpMethod = 2
	HttpAction_PUT                HttpAction_HttpMethod = 3
	HttpAction_DELETE             HttpAction_HttpMethod = 4
	HttpAction_HEAD               HttpAction_HttpMethod = 5
)

// Enum value maps for HttpAction_HttpMethod.
var (
	HttpAction_HttpMethod_name = map[int32]string{
		0: "METHOD_UNSPECIFIED",
		1: "GET",
		2: "POST",
		3: "PUT",
		4: "DELETE",
		5: "HEAD",
	}
	HttpAction_HttpMethod_value = map[string]int32{
		"METHOD_UNSPECIFIED": 0,
		"GET":                1,
		"POST":               2,
		"PUT":                3,
		"DELETE":             4,
		"HEAD":               5,
	}
)

func (x HttpAction_HttpMethod) Enum() *HttpAction_HttpMethod {
	p := new(HttpAction_HttpMethod)
	*p = x
	return p
}

func (x HttpAction_HttpMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpAction_HttpMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_action_http_proto_enumTypes[0].Descriptor()
}

func (HttpAction_HttpMethod) Type() protoreflect.EnumType {
	return &file_action_http_proto_enumTypes[0]
}

func (x HttpAction_HttpMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// HttpAction is used to perform HTTP requests.
type HttpAction struct {
	state                    protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Method        HttpAction_HttpMethod         `protobuf:"varint,1,opt,name=method,proto3,enum=tsunami_templated_detector.HttpAction_HttpMethod"`
	xxx_hidden_Uri           []string                      `protobuf:"bytes,2,rep,name=uri,proto3"`
	xxx_hidden_Headers       *[]*HttpAction_HttpHeader     `protobuf:"bytes,3,rep,name=headers,proto3"`
	xxx_hidden_Data          string                        `protobuf:"bytes,4,opt,name=data,proto3"`
	xxx_hidden_Response      *HttpAction_HttpResponse      `protobuf:"bytes,5,opt,name=response,proto3"`
	xxx_hidden_ClientOptions *HttpAction_HttpClientOptions `protobuf:"bytes,6,opt,name=client_options,json=clientOptions,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HttpAction) Reset() {
	*x = HttpAction{}
	mi := &file_action_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction) ProtoMessage() {}

func (x *HttpAction) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction) GetMethod() HttpAction_HttpMethod {
	if x != nil {
		return x.xxx_hidden_Method
	}
	return HttpAction_METHOD_UNSPECIFIED
}

func (x *HttpAction) GetUri() []string {
	if x != nil {
		return x.xxx_hidden_Uri
	}
	return nil
}

func (x *HttpAction) GetHeaders() []*HttpAction_HttpHeader {
	if x != nil {
		if x.xxx_hidden_Headers != nil {
			return *x.xxx_hidden_Headers
		}
	}
	return nil
}

func (x *HttpAction) GetData() string {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return ""
}

func (x *HttpAction) GetResponse() *HttpAction_HttpResponse {
	if x != nil {
		return x.xxx_hidden_Response
	}
	return nil
}

func (x *HttpAction) GetClientOptions() *HttpAction_HttpClientOptions {
	if x != nil {
		return x.xxx_hidden_ClientOptions
	}
	return nil
}

func (x *HttpAction) SetMethod(v HttpAction_HttpMethod) {
	x.xxx_hidden_Method = v
}

func (x *HttpAction) SetUri(v []string) {
	x.xxx_hidden_Uri = v
}

func (x *HttpAction) SetHeaders(v []*HttpAction_HttpHeader) {
	x.xxx_hidden_Headers = &v
}

func (x *HttpAction) SetData(v string) {
	x.xxx_hidden_Data = v
}

func (x *HttpAction) SetResponse(v *HttpAction_HttpResponse) {
	x.xxx_hidden_Response = v
}

func (x *HttpAction) SetClientOptions(v *HttpAction_HttpClientOptions) {
	x.xxx_hidden_ClientOptions = v
}

func (x *HttpAction) HasResponse() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Response != nil
}

func (x *HttpAction) HasClientOptions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ClientOptions != nil
}

func (x *HttpAction) ClearResponse() {
	x.xxx_hidden_Response = nil
}

func (x *HttpAction) ClearClientOptions() {
	x.xxx_hidden_ClientOptions = nil
}

type HttpAction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The HTTP method to use (e.g. GET, POST, ...).
	Method HttpAction_HttpMethod
	// One of several URIs to try (e.g. "/", "/somepage", ...). Tsunami will try
	// each URI until one succeeds. Each URI will reuse the other parameters of
	// the action (headers, extractions, etc...).
	Uri []string
	// HTTP headers to add to the request.
	Headers []*HttpAction_HttpHeader
	// Body of the HTTP request. Tsunami does not perform additional encoding of
	// this field. It should contain the raw data to be sent.
	Data string
	// Actions to be performed on the HTTP response.
	Response *HttpAction_HttpResponse
	// Configuration of the HTTP client.
	ClientOptions *HttpAction_HttpClientOptions
}

func (b0 HttpAction_builder) Build() *HttpAction {
	m0 := &HttpAction{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Method = b.Method
	x.xxx_hidden_Uri = b.Uri
	x.xxx_hidden_Headers = &b.Headers
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Response = b.Response
	x.xxx_hidden_ClientOptions = b.ClientOptions
	return m0
}

type HttpAction_HttpHeader struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name  string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HttpAction_HttpHeader) Reset() {
	*x = HttpAction_HttpHeader{}
	mi := &file_action_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpHeader) ProtoMessage() {}

func (x *HttpAction_HttpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction_HttpHeader) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *HttpAction_HttpHeader) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *HttpAction_HttpHeader) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *HttpAction_HttpHeader) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type HttpAction_HttpHeader_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of the header.
	Name string
	// The value of the header.
	Value string
}

func (b0 HttpAction_HttpHeader_builder) Build() *HttpAction_HttpHeader {
	m0 := &HttpAction_HttpHeader{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Value = b.Value
	return m0
}

type HttpAction_HttpResponse struct {
	state                   protoimpl.MessageState                 `protogen:"opaque.v1"`
	xxx_hidden_HttpStatus   int64                                  `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3"`
	xxx_hidden_Expectations isHttpAction_HttpResponse_Expectations `protobuf_oneof:"expectations"`
	xxx_hidden_Extractions  isHttpAction_HttpResponse_Extractions  `protobuf_oneof:"extractions"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HttpAction_HttpResponse) Reset() {
	*x = HttpAction_HttpResponse{}
	mi := &file_action_http_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpResponse) ProtoMessage() {}

func (x *HttpAction_HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction_HttpResponse) GetHttpStatus() int64 {
	if x != nil {
		return x.xxx_hidden_HttpStatus
	}
	return 0
}

func (x *HttpAction_HttpResponse) GetExpectAny() *HttpAction_HttpResponse_ExpectAny {
	if x != nil {
		if x, ok := x.xxx_hidden_Expectations.(*httpAction_HttpResponse_ExpectAny_); ok {
			return x.ExpectAny
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse) GetExpectAll() *HttpAction_HttpResponse_ExpectAll {
	if x != nil {
		if x, ok := x.xxx_hidden_Expectations.(*httpAction_HttpResponse_ExpectAll_); ok {
			return x.ExpectAll
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse) GetExtractAny() *HttpAction_HttpResponse_ExtractAny {
	if x != nil {
		if x, ok := x.xxx_hidden_Extractions.(*httpAction_HttpResponse_ExtractAny_); ok {
			return x.ExtractAny
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse) GetExtractAll() *HttpAction_HttpResponse_ExtractAll {
	if x != nil {
		if x, ok := x.xxx_hidden_Extractions.(*httpAction_HttpResponse_ExtractAll_); ok {
			return x.ExtractAll
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse) SetHttpStatus(v int64) {
	x.xxx_hidden_HttpStatus = v
}

func (x *HttpAction_HttpResponse) SetExpectAny(v *HttpAction_HttpResponse_ExpectAny) {
	if v == nil {
		x.xxx_hidden_Expectations = nil
		return
	}
	x.xxx_hidden_Expectations = &httpAction_HttpResponse_ExpectAny_{v}
}

func (x *HttpAction_HttpResponse) SetExpectAll(v *HttpAction_HttpResponse_ExpectAll) {
	if v == nil {
		x.xxx_hidden_Expectations = nil
		return
	}
	x.xxx_hidden_Expectations = &httpAction_HttpResponse_ExpectAll_{v}
}

func (x *HttpAction_HttpResponse) SetExtractAny(v *HttpAction_HttpResponse_ExtractAny) {
	if v == nil {
		x.xxx_hidden_Extractions = nil
		return
	}
	x.xxx_hidden_Extractions = &httpAction_HttpResponse_ExtractAny_{v}
}

func (x *HttpAction_HttpResponse) SetExtractAll(v *HttpAction_HttpResponse_ExtractAll) {
	if v == nil {
		x.xxx_hidden_Extractions = nil
		return
	}
	x.xxx_hidden_Extractions = &httpAction_HttpResponse_ExtractAll_{v}
}

func (x *HttpAction_HttpResponse) HasExpectations() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Expectations != nil
}

func (x *HttpAction_HttpResponse) HasExpectAny() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Expectations.(*httpAction_HttpResponse_ExpectAny_)
	return ok
}

func (x *HttpAction_HttpResponse) HasExpectAll() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Expectations.(*httpAction_HttpResponse_ExpectAll_)
	return ok
}

func (x *HttpAction_HttpResponse) HasExtractions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Extractions != nil
}

func (x *HttpAction_HttpResponse) HasExtractAny() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Extractions.(*httpAction_HttpResponse_ExtractAny_)
	return ok
}

func (x *HttpAction_HttpResponse) HasExtractAll() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Extractions.(*httpAction_HttpResponse_ExtractAll_)
	return ok
}

func (x *HttpAction_HttpResponse) ClearExpectations() {
	x.xxx_hidden_Expectations = nil
}

func (x *HttpAction_HttpResponse) ClearExpectAny() {
	if _, ok := x.xxx_hidden_Expectations.(*httpAction_HttpResponse_ExpectAny_); ok {
		x.xxx_hidden_Expectations = nil
	}
}

func (x *HttpAction_HttpResponse) ClearExpectAll() {
	if _, ok := x.xxx_hidden_Expectations.(*httpAction_HttpResponse_ExpectAll_); ok {
		x.xxx_hidden_Expectations = nil
	}
}

func (x *HttpAction_HttpResponse) ClearExtractions() {
	x.xxx_hidden_Extractions = nil
}

func (x *HttpAction_HttpResponse) ClearExtractAny() {
	if _, ok := x.xxx_hidden_Extractions.(*httpAction_HttpResponse_ExtractAny_); ok {
		x.xxx_hidden_Extractions = nil
	}
}

func (x *HttpAction_HttpResponse) ClearExtractAll() {
	if _, ok := x.xxx_hidden_Extractions.(*httpAction_HttpResponse_ExtractAll_); ok {
		x.xxx_hidden_Extractions = nil
	}
}

const HttpAction_HttpResponse_Expectations_not_set_case case_HttpAction_HttpResponse_Expectations = 0
const HttpAction_HttpResponse_ExpectAny_case case_HttpAction_HttpResponse_Expectations = 2
const HttpAction_HttpResponse_ExpectAll_case case_HttpAction_HttpResponse_Expectations = 3

func (x *HttpAction_HttpResponse) WhichExpectations() case_HttpAction_HttpResponse_Expectations {
	if x == nil {
		return HttpAction_HttpResponse_Expectations_not_set_case
	}
	switch x.xxx_hidden_Expectations.(type) {
	case *httpAction_HttpResponse_ExpectAny_:
		return HttpAction_HttpResponse_ExpectAny_case
	case *httpAction_HttpResponse_ExpectAll_:
		return HttpAction_HttpResponse_ExpectAll_case
	default:
		return HttpAction_HttpResponse_Expectations_not_set_case
	}
}

const HttpAction_HttpResponse_Extractions_not_set_case case_HttpAction_HttpResponse_Extractions = 0
const HttpAction_HttpResponse_ExtractAny_case case_HttpAction_HttpResponse_Extractions = 4
const HttpAction_HttpResponse_ExtractAll_case case_HttpAction_HttpResponse_Extractions = 5

func (x *HttpAction_HttpResponse) WhichExtractions() case_HttpAction_HttpResponse_Extractions {
	if x == nil {
		return HttpAction_HttpResponse_Extractions_not_set_case
	}
	switch x.xxx_hidden_Extractions.(type) {
	case *httpAction_HttpResponse_ExtractAny_:
		return HttpAction_HttpResponse_ExtractAny_case
	case *httpAction_HttpResponse_ExtractAll_:
		return HttpAction_HttpResponse_ExtractAll_case
	default:
		return HttpAction_HttpResponse_Extractions_not_set_case
	}
}

type HttpAction_HttpResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The HTTP status code to expect from the response.
	HttpStatus int64
	// A set of expectations to check for on the response. For example, does
	// the header contains a specific value?
	// The expectations can either be ALL (all conditions must be met) or ANY
	// (matching stops at the first met condition).

	// Fields of oneof xxx_hidden_Expectations:
	ExpectAny *HttpAction_HttpResponse_ExpectAny
	ExpectAll *HttpAction_HttpResponse_ExpectAll
	// -- end of xxx_hidden_Expectations
	// Extract a value from the response and stores it in a variable. Failure
	// to extract all or one value (All/Any) causes the action to fail.
	//
	// ExtractAny: Matching stops at the first successful extraction.
	// ExtractAll: All extractions must be successful and modifies the current
	//             environment.
	//
	// IMPORTANT NOTE: Any extractions can be used to circumvent slight version
	// variation in a product that would result in the same variable being set.
	// For example, matching a version tag that might be present in different
	// HTML tags depending on the version. It is STRONGLY recommended not to set
	// different variables using an ExtractAny as there will be no guarantee
	// which variable is set.

	// Fields of oneof xxx_hidden_Extractions:
	ExtractAny *HttpAction_HttpResponse_ExtractAny
	ExtractAll *HttpAction_HttpResponse_ExtractAll
	// -- end of xxx_hidden_Extractions
}

func (b0 HttpAction_HttpResponse_builder) Build() *HttpAction_HttpResponse {
	m0 := &HttpAction_HttpResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_HttpStatus = b.HttpStatus
	if b.ExpectAny != nil {
		x.xxx_hidden_Expectations = &httpAction_HttpResponse_ExpectAny_{b.ExpectAny}
	}
	if b.ExpectAll != nil {
		x.xxx_hidden_Expectations = &httpAction_HttpResponse_ExpectAll_{b.ExpectAll}
	}
	if b.ExtractAny != nil {
		x.xxx_hidden_Extractions = &httpAction_HttpResponse_ExtractAny_{b.ExtractAny}
	}
	if b.ExtractAll != nil {
		x.xxx_hidden_Extractions = &httpAction_HttpResponse_ExtractAll_{b.ExtractAll}
	}
	return m0
}

type case_HttpAction_HttpResponse_Expectations protoreflect.FieldNumber

func (x case_HttpAction_HttpResponse_Expectations) String() string {
	md := file_action_http_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type case_HttpAction_HttpResponse_Extractions protoreflect.FieldNumber

func (x case_HttpAction_HttpResponse_Extractions) String() string {
	md := file_action_http_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isHttpAction_HttpResponse_Expectations interface {
	isHttpAction_HttpResponse_Expectations()
}

type httpAction_HttpResponse_ExpectAny_ struct {
	ExpectAny *HttpAction_HttpResponse_ExpectAny `protobuf:"bytes,2,opt,name=expect_any,json=expectAny,proto3,oneof"`
}

type httpAction_HttpResponse_ExpectAll_ struct {
	ExpectAll *HttpAction_HttpResponse_ExpectAll `protobuf:"bytes,3,opt,name=expect_all,json=expectAll,proto3,oneof"`
}

func (*httpAction_HttpResponse_ExpectAny_) isHttpAction_HttpResponse_Expectations() {}

func (*httpAction_HttpResponse_ExpectAll_) isHttpAction_HttpResponse_Expectations() {}

type isHttpAction_HttpResponse_Extractions interface {
	isHttpAction_HttpResponse_Extractions()
}

type httpAction_HttpResponse_ExtractAny_ struct {
	ExtractAny *HttpAction_HttpResponse_ExtractAny `protobuf:"bytes,4,opt,name=extract_any,json=extractAny,proto3,oneof"`
}

type httpAction_HttpResponse_ExtractAll_ struct {
	ExtractAll *HttpAction_HttpResponse_ExtractAll `protobuf:"bytes,5,opt,name=extract_all,json=extractAll,proto3,oneof"`
}

func (*httpAction_HttpResponse_ExtractAny_) isHttpAction_HttpResponse_Extractions() {}

func (*httpAction_HttpResponse_ExtractAll_) isHttpAction_HttpResponse_Extractions() {}

type HttpAction_HttpClientOptions struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DisableFollowRedirects bool                   `protobuf:"varint,1,opt,name=disable_follow_redirects,json=disableFollowRedirects,proto3"`
	xxx_hidden_IgnoreHttpClientErrors bool                   `protobuf:"varint,2,opt,name=ignore_http_client_errors,json=ignoreHttpClientErrors,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *HttpAction_HttpClientOptions) Reset() {
	*x = HttpAction_HttpClientOptions{}
	mi := &file_action_http_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpClientOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpClientOptions) ProtoMessage() {}

func (x *HttpAction_HttpClientOptions) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction_HttpClientOptions) GetDisableFollowRedirects() bool {
	if x != nil {
		return x.xxx_hidden_DisableFollowRedirects
	}
	return false
}

func (x *HttpAction_HttpClientOptions) GetIgnoreHttpClientErrors() bool {
	if x != nil {
		return x.xxx_hidden_IgnoreHttpClientErrors
	}
	return false
}

func (x *HttpAction_HttpClientOptions) SetDisableFollowRedirects(v bool) {
	x.xxx_hidden_DisableFollowRedirects = v
}

func (x *HttpAction_HttpClientOptions) SetIgnoreHttpClientErrors(v bool) {
	x.xxx_hidden_IgnoreHttpClientErrors = v
}

type HttpAction_HttpClientOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether the HTTP client should follow redirects.
	// By default, we follow redirects so this flag can be used to disable this
	// behavior.
	DisableFollowRedirects bool
	// Whether the HTTP client exceptions should be ignored.
	//
	// By default, any HTTP client failure will fail the plugin execution and
	// checks are not performed. However, in some cases the tested server might
	// just execute a payload and hang forever and the HTTP client will timeout.
	//
	// Ignoring HTTP client exceptions will allow the workflow to proceed with
	// vulnerability verifications, like checking whether callback servers
	// received an interaction.
	IgnoreHttpClientErrors bool
}

func (b0 HttpAction_HttpClientOptions_builder) Build() *HttpAction_HttpClientOptions {
	m0 := &HttpAction_HttpClientOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DisableFollowRedirects = b.DisableFollowRedirects
	x.xxx_hidden_IgnoreHttpClientErrors = b.IgnoreHttpClientErrors
	return m0
}

type HttpAction_HttpResponse_Header struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HttpAction_HttpResponse_Header) Reset() {
	*x = HttpAction_HttpResponse_Header{}
	mi := &file_action_http_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpResponse_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpResponse_Header) ProtoMessage() {}

func (x *HttpAction_HttpResponse_Header) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction_HttpResponse_Header) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *HttpAction_HttpResponse_Header) SetName(v string) {
	x.xxx_hidden_Name = v
}

type HttpAction_HttpResponse_Header_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the header.
	Name string
}

func (b0 HttpAction_HttpResponse_Header_builder) Build() *HttpAction_HttpResponse_Header {
	m0 := &HttpAction_HttpResponse_Header{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

type HttpAction_HttpResponse_Body struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpAction_HttpResponse_Body) Reset() {
	*x = HttpAction_HttpResponse_Body{}
	mi := &file_action_http_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpResponse_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpResponse_Body) ProtoMessage() {}

func (x *HttpAction_HttpResponse_Body) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HttpAction_HttpResponse_Body_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 HttpAction_HttpResponse_Body_builder) Build() *HttpAction_HttpResponse_Body {
	m0 := &HttpAction_HttpResponse_Body{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type HttpAction_HttpResponse_Extract struct {
	state                   protoimpl.MessageState                    `protogen:"opaque.v1"`
	xxx_hidden_VariableName string                                    `protobuf:"bytes,1,opt,name=variable_name,json=variableName,proto3"`
	xxx_hidden_Regexp       string                                    `protobuf:"bytes,2,opt,name=regexp,proto3"`
	xxx_hidden_Extract      isHttpAction_HttpResponse_Extract_Extract `protobuf_oneof:"extract"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HttpAction_HttpResponse_Extract) Reset() {
	*x = HttpAction_HttpResponse_Extract{}
	mi := &file_action_http_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpResponse_Extract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpResponse_Extract) ProtoMessage() {}

func (x *HttpAction_HttpResponse_Extract) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction_HttpResponse_Extract) GetVariableName() string {
	if x != nil {
		return x.xxx_hidden_VariableName
	}
	return ""
}

func (x *HttpAction_HttpResponse_Extract) GetRegexp() string {
	if x != nil {
		return x.xxx_hidden_Regexp
	}
	return ""
}

func (x *HttpAction_HttpResponse_Extract) GetFromHeader() *HttpAction_HttpResponse_Header {
	if x != nil {
		if x, ok := x.xxx_hidden_Extract.(*httpAction_HttpResponse_Extract_FromHeader); ok {
			return x.FromHeader
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse_Extract) GetFromBody() *HttpAction_HttpResponse_Body {
	if x != nil {
		if x, ok := x.xxx_hidden_Extract.(*httpAction_HttpResponse_Extract_FromBody); ok {
			return x.FromBody
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse_Extract) SetVariableName(v string) {
	x.xxx_hidden_VariableName = v
}

func (x *HttpAction_HttpResponse_Extract) SetRegexp(v string) {
	x.xxx_hidden_Regexp = v
}

func (x *HttpAction_HttpResponse_Extract) SetFromHeader(v *HttpAction_HttpResponse_Header) {
	if v == nil {
		x.xxx_hidden_Extract = nil
		return
	}
	x.xxx_hidden_Extract = &httpAction_HttpResponse_Extract_FromHeader{v}
}

func (x *HttpAction_HttpResponse_Extract) SetFromBody(v *HttpAction_HttpResponse_Body) {
	if v == nil {
		x.xxx_hidden_Extract = nil
		return
	}
	x.xxx_hidden_Extract = &httpAction_HttpResponse_Extract_FromBody{v}
}

func (x *HttpAction_HttpResponse_Extract) HasExtract() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Extract != nil
}

func (x *HttpAction_HttpResponse_Extract) HasFromHeader() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Extract.(*httpAction_HttpResponse_Extract_FromHeader)
	return ok
}

func (x *HttpAction_HttpResponse_Extract) HasFromBody() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Extract.(*httpAction_HttpResponse_Extract_FromBody)
	return ok
}

func (x *HttpAction_HttpResponse_Extract) ClearExtract() {
	x.xxx_hidden_Extract = nil
}

func (x *HttpAction_HttpResponse_Extract) ClearFromHeader() {
	if _, ok := x.xxx_hidden_Extract.(*httpAction_HttpResponse_Extract_FromHeader); ok {
		x.xxx_hidden_Extract = nil
	}
}

func (x *HttpAction_HttpResponse_Extract) ClearFromBody() {
	if _, ok := x.xxx_hidden_Extract.(*httpAction_HttpResponse_Extract_FromBody); ok {
		x.xxx_hidden_Extract = nil
	}
}

const HttpAction_HttpResponse_Extract_Extract_not_set_case case_HttpAction_HttpResponse_Extract_Extract = 0
const HttpAction_HttpResponse_Extract_FromHeader_case case_HttpAction_HttpResponse_Extract_Extract = 3
const HttpAction_HttpResponse_Extract_FromBody_case case_HttpAction_HttpResponse_Extract_Extract = 4

func (x *HttpAction_HttpResponse_Extract) WhichExtract() case_HttpAction_HttpResponse_Extract_Extract {
	if x == nil {
		return HttpAction_HttpResponse_Extract_Extract_not_set_case
	}
	switch x.xxx_hidden_Extract.(type) {
	case *httpAction_HttpResponse_Extract_FromHeader:
		return HttpAction_HttpResponse_Extract_FromHeader_case
	case *httpAction_HttpResponse_Extract_FromBody:
		return HttpAction_HttpResponse_Extract_FromBody_case
	default:
		return HttpAction_HttpResponse_Extract_Extract_not_set_case
	}
}

type HttpAction_HttpResponse_Extract_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of the variable to store the extracted value in.
	VariableName string
	// The regexp to use to extract the value from the response.
	Regexp string
	// Where to extract the value from.

	// Fields of oneof xxx_hidden_Extract:
	FromHeader *HttpAction_HttpResponse_Header
	FromBody   *HttpAction_HttpResponse_Body
	// -- end of xxx_hidden_Extract
}

func (b0 HttpAction_HttpResponse_Extract_builder) Build() *HttpAction_HttpResponse_Extract {
	m0 := &HttpAction_HttpResponse_Extract{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_VariableName = b.VariableName
	x.xxx_hidden_Regexp = b.Regexp
	if b.FromHeader != nil {
		x.xxx_hidden_Extract = &httpAction_HttpResponse_Extract_FromHeader{b.FromHeader}
	}
	if b.FromBody != nil {
		x.xxx_hidden_Extract = &httpAction_HttpResponse_Extract_FromBody{b.FromBody}
	}
	return m0
}

type case_HttpAction_HttpResponse_Extract_Extract protoreflect.FieldNumber

func (x case_HttpAction_HttpResponse_Extract_Extract) String() string {
	md := file_action_http_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isHttpAction_HttpResponse_Extract_Extract interface {
	isHttpAction_HttpResponse_Extract_Extract()
}

type httpAction_HttpResponse_Extract_FromHeader struct {
	FromHeader *HttpAction_HttpResponse_Header `protobuf:"bytes,3,opt,name=from_header,json=fromHeader,proto3,oneof"`
}

type httpAction_HttpResponse_Extract_FromBody struct {
	FromBody *HttpAction_HttpResponse_Body `protobuf:"bytes,4,opt,name=from_body,json=fromBody,proto3,oneof"`
}

func (*httpAction_HttpResponse_Extract_FromHeader) isHttpAction_HttpResponse_Extract_Extract() {}

func (*httpAction_HttpResponse_Extract_FromBody) isHttpAction_HttpResponse_Extract_Extract() {}

type HttpAction_HttpResponse_ExtractAll struct {
	state               protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_Patterns *[]*HttpAction_HttpResponse_Extract `protobuf:"bytes,1,rep,name=patterns,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HttpAction_HttpResponse_ExtractAll) Reset() {
	*x = HttpAction_HttpResponse_ExtractAll{}
	mi := &file_action_http_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpResponse_ExtractAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpResponse_ExtractAll) ProtoMessage() {}

func (x *HttpAction_HttpResponse_ExtractAll) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction_HttpResponse_ExtractAll) GetPatterns() []*HttpAction_HttpResponse_Extract {
	if x != nil {
		if x.xxx_hidden_Patterns != nil {
			return *x.xxx_hidden_Patterns
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse_ExtractAll) SetPatterns(v []*HttpAction_HttpResponse_Extract) {
	x.xxx_hidden_Patterns = &v
}

type HttpAction_HttpResponse_ExtractAll_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Patterns []*HttpAction_HttpResponse_Extract
}

func (b0 HttpAction_HttpResponse_ExtractAll_builder) Build() *HttpAction_HttpResponse_ExtractAll {
	m0 := &HttpAction_HttpResponse_ExtractAll{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Patterns = &b.Patterns
	return m0
}

type HttpAction_HttpResponse_ExtractAny struct {
	state               protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_Patterns *[]*HttpAction_HttpResponse_Extract `protobuf:"bytes,1,rep,name=patterns,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HttpAction_HttpResponse_ExtractAny) Reset() {
	*x = HttpAction_HttpResponse_ExtractAny{}
	mi := &file_action_http_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpResponse_ExtractAny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpResponse_ExtractAny) ProtoMessage() {}

func (x *HttpAction_HttpResponse_ExtractAny) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction_HttpResponse_ExtractAny) GetPatterns() []*HttpAction_HttpResponse_Extract {
	if x != nil {
		if x.xxx_hidden_Patterns != nil {
			return *x.xxx_hidden_Patterns
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse_ExtractAny) SetPatterns(v []*HttpAction_HttpResponse_Extract) {
	x.xxx_hidden_Patterns = &v
}

type HttpAction_HttpResponse_ExtractAny_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Patterns []*HttpAction_HttpResponse_Extract
}

func (b0 HttpAction_HttpResponse_ExtractAny_builder) Build() *HttpAction_HttpResponse_ExtractAny {
	m0 := &HttpAction_HttpResponse_ExtractAny{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Patterns = &b.Patterns
	return m0
}

type HttpAction_HttpResponse_Expectation struct {
	state                  protoimpl.MessageState                            `protogen:"opaque.v1"`
	xxx_hidden_Contains    string                                            `protobuf:"bytes,1,opt,name=contains,proto3"`
	xxx_hidden_Expectation isHttpAction_HttpResponse_Expectation_Expectation `protobuf_oneof:"expectation"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HttpAction_HttpResponse_Expectation) Reset() {
	*x = HttpAction_HttpResponse_Expectation{}
	mi := &file_action_http_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpResponse_Expectation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpResponse_Expectation) ProtoMessage() {}

func (x *HttpAction_HttpResponse_Expectation) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction_HttpResponse_Expectation) GetContains() string {
	if x != nil {
		return x.xxx_hidden_Contains
	}
	return ""
}

func (x *HttpAction_HttpResponse_Expectation) GetHeader() *HttpAction_HttpResponse_Header {
	if x != nil {
		if x, ok := x.xxx_hidden_Expectation.(*httpAction_HttpResponse_Expectation_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse_Expectation) GetBody() *HttpAction_HttpResponse_Body {
	if x != nil {
		if x, ok := x.xxx_hidden_Expectation.(*httpAction_HttpResponse_Expectation_Body); ok {
			return x.Body
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse_Expectation) SetContains(v string) {
	x.xxx_hidden_Contains = v
}

func (x *HttpAction_HttpResponse_Expectation) SetHeader(v *HttpAction_HttpResponse_Header) {
	if v == nil {
		x.xxx_hidden_Expectation = nil
		return
	}
	x.xxx_hidden_Expectation = &httpAction_HttpResponse_Expectation_Header{v}
}

func (x *HttpAction_HttpResponse_Expectation) SetBody(v *HttpAction_HttpResponse_Body) {
	if v == nil {
		x.xxx_hidden_Expectation = nil
		return
	}
	x.xxx_hidden_Expectation = &httpAction_HttpResponse_Expectation_Body{v}
}

func (x *HttpAction_HttpResponse_Expectation) HasExpectation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Expectation != nil
}

func (x *HttpAction_HttpResponse_Expectation) HasHeader() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Expectation.(*httpAction_HttpResponse_Expectation_Header)
	return ok
}

func (x *HttpAction_HttpResponse_Expectation) HasBody() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Expectation.(*httpAction_HttpResponse_Expectation_Body)
	return ok
}

func (x *HttpAction_HttpResponse_Expectation) ClearExpectation() {
	x.xxx_hidden_Expectation = nil
}

func (x *HttpAction_HttpResponse_Expectation) ClearHeader() {
	if _, ok := x.xxx_hidden_Expectation.(*httpAction_HttpResponse_Expectation_Header); ok {
		x.xxx_hidden_Expectation = nil
	}
}

func (x *HttpAction_HttpResponse_Expectation) ClearBody() {
	if _, ok := x.xxx_hidden_Expectation.(*httpAction_HttpResponse_Expectation_Body); ok {
		x.xxx_hidden_Expectation = nil
	}
}

const HttpAction_HttpResponse_Expectation_Expectation_not_set_case case_HttpAction_HttpResponse_Expectation_Expectation = 0
const HttpAction_HttpResponse_Expectation_Header_case case_HttpAction_HttpResponse_Expectation_Expectation = 2
const HttpAction_HttpResponse_Expectation_Body_case case_HttpAction_HttpResponse_Expectation_Expectation = 3

func (x *HttpAction_HttpResponse_Expectation) WhichExpectation() case_HttpAction_HttpResponse_Expectation_Expectation {
	if x == nil {
		return HttpAction_HttpResponse_Expectation_Expectation_not_set_case
	}
	switch x.xxx_hidden_Expectation.(type) {
	case *httpAction_HttpResponse_Expectation_Header:
		return HttpAction_HttpResponse_Expectation_Header_case
	case *httpAction_HttpResponse_Expectation_Body:
		return HttpAction_HttpResponse_Expectation_Body_case
	default:
		return HttpAction_HttpResponse_Expectation_Expectation_not_set_case
	}
}

type HttpAction_HttpResponse_Expectation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The value to expect in the response.
	Contains string
	// Where to expect the value.

	// Fields of oneof xxx_hidden_Expectation:
	Header *HttpAction_HttpResponse_Header
	Body   *HttpAction_HttpResponse_Body
	// -- end of xxx_hidden_Expectation
}

func (b0 HttpAction_HttpResponse_Expectation_builder) Build() *HttpAction_HttpResponse_Expectation {
	m0 := &HttpAction_HttpResponse_Expectation{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Contains = b.Contains
	if b.Header != nil {
		x.xxx_hidden_Expectation = &httpAction_HttpResponse_Expectation_Header{b.Header}
	}
	if b.Body != nil {
		x.xxx_hidden_Expectation = &httpAction_HttpResponse_Expectation_Body{b.Body}
	}
	return m0
}

type case_HttpAction_HttpResponse_Expectation_Expectation protoreflect.FieldNumber

func (x case_HttpAction_HttpResponse_Expectation_Expectation) String() string {
	md := file_action_http_proto_msgTypes[9].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isHttpAction_HttpResponse_Expectation_Expectation interface {
	isHttpAction_HttpResponse_Expectation_Expectation()
}

type httpAction_HttpResponse_Expectation_Header struct {
	Header *HttpAction_HttpResponse_Header `protobuf:"bytes,2,opt,name=header,proto3,oneof"`
}

type httpAction_HttpResponse_Expectation_Body struct {
	Body *HttpAction_HttpResponse_Body `protobuf:"bytes,3,opt,name=body,proto3,oneof"`
}

func (*httpAction_HttpResponse_Expectation_Header) isHttpAction_HttpResponse_Expectation_Expectation() {
}

func (*httpAction_HttpResponse_Expectation_Body) isHttpAction_HttpResponse_Expectation_Expectation() {
}

type HttpAction_HttpResponse_ExpectAny struct {
	state                 protoimpl.MessageState                  `protogen:"opaque.v1"`
	xxx_hidden_Conditions *[]*HttpAction_HttpResponse_Expectation `protobuf:"bytes,1,rep,name=conditions,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HttpAction_HttpResponse_ExpectAny) Reset() {
	*x = HttpAction_HttpResponse_ExpectAny{}
	mi := &file_action_http_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpResponse_ExpectAny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpResponse_ExpectAny) ProtoMessage() {}

func (x *HttpAction_HttpResponse_ExpectAny) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction_HttpResponse_ExpectAny) GetConditions() []*HttpAction_HttpResponse_Expectation {
	if x != nil {
		if x.xxx_hidden_Conditions != nil {
			return *x.xxx_hidden_Conditions
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse_ExpectAny) SetConditions(v []*HttpAction_HttpResponse_Expectation) {
	x.xxx_hidden_Conditions = &v
}

type HttpAction_HttpResponse_ExpectAny_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Conditions []*HttpAction_HttpResponse_Expectation
}

func (b0 HttpAction_HttpResponse_ExpectAny_builder) Build() *HttpAction_HttpResponse_ExpectAny {
	m0 := &HttpAction_HttpResponse_ExpectAny{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Conditions = &b.Conditions
	return m0
}

type HttpAction_HttpResponse_ExpectAll struct {
	state                 protoimpl.MessageState                  `protogen:"opaque.v1"`
	xxx_hidden_Conditions *[]*HttpAction_HttpResponse_Expectation `protobuf:"bytes,1,rep,name=conditions,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HttpAction_HttpResponse_ExpectAll) Reset() {
	*x = HttpAction_HttpResponse_ExpectAll{}
	mi := &file_action_http_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAction_HttpResponse_ExpectAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAction_HttpResponse_ExpectAll) ProtoMessage() {}

func (x *HttpAction_HttpResponse_ExpectAll) ProtoReflect() protoreflect.Message {
	mi := &file_action_http_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpAction_HttpResponse_ExpectAll) GetConditions() []*HttpAction_HttpResponse_Expectation {
	if x != nil {
		if x.xxx_hidden_Conditions != nil {
			return *x.xxx_hidden_Conditions
		}
	}
	return nil
}

func (x *HttpAction_HttpResponse_ExpectAll) SetConditions(v []*HttpAction_HttpResponse_Expectation) {
	x.xxx_hidden_Conditions = &v
}

type HttpAction_HttpResponse_ExpectAll_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Conditions []*HttpAction_HttpResponse_Expectation
}

func (b0 HttpAction_HttpResponse_ExpectAll_builder) Build() *HttpAction_HttpResponse_ExpectAll {
	m0 := &HttpAction_HttpResponse_ExpectAll{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Conditions = &b.Conditions
	return m0
}

var File_action_http_proto protoreflect.FileDescriptor

const file_action_http_proto_rawDesc = "" +
	"\n" +
	"\x11action_http.proto\x12\x1atsunami_templated_detector\"\xab\x10\n" +
	"\n" +
	"HttpAction\x12I\n" +
	"\x06method\x18\x01 \x01(\x0e21.tsunami_templated_detector.HttpAction.HttpMethodR\x06method\x12\x10\n" +
	"\x03uri\x18\x02 \x03(\tR\x03uri\x12K\n" +
	"\aheaders\x18\x03 \x03(\v21.tsunami_templated_detector.HttpAction.HttpHeaderR\aheaders\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12O\n" +
	"\bresponse\x18\x05 \x01(\v23.tsunami_templated_detector.HttpAction.HttpResponseR\bresponse\x12_\n" +
	"\x0eclient_options\x18\x06 \x01(\v28.tsunami_templated_detector.HttpAction.HttpClientOptionsR\rclientOptions\x1a6\n" +
	"\n" +
	"HttpHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x1a\x91\v\n" +
	"\fHttpResponse\x12\x1f\n" +
	"\vhttp_status\x18\x01 \x01(\x03R\n" +
	"httpStatus\x12^\n" +
	"\n" +
	"expect_any\x18\x02 \x01(\v2=.tsunami_templated_detector.HttpAction.HttpResponse.ExpectAnyH\x00R\texpectAny\x12^\n" +
	"\n" +
	"expect_all\x18\x03 \x01(\v2=.tsunami_templated_detector.HttpAction.HttpResponse.ExpectAllH\x00R\texpectAll\x12a\n" +
	"\vextract_any\x18\x04 \x01(\v2>.tsunami_templated_detector.HttpAction.HttpResponse.ExtractAnyH\x01R\n" +
	"extractAny\x12a\n" +
	"\vextract_all\x18\x05 \x01(\v2>.tsunami_templated_detector.HttpAction.HttpResponse.ExtractAllH\x01R\n" +
	"extractAll\x1a\x1c\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a\x06\n" +
	"\x04Body\x1a\x89\x02\n" +
	"\aExtract\x12#\n" +
	"\rvariable_name\x18\x01 \x01(\tR\fvariableName\x12\x16\n" +
	"\x06regexp\x18\x02 \x01(\tR\x06regexp\x12]\n" +
	"\vfrom_header\x18\x03 \x01(\v2:.tsunami_templated_detector.HttpAction.HttpResponse.HeaderH\x00R\n" +
	"fromHeader\x12W\n" +
	"\tfrom_body\x18\x04 \x01(\v28.tsunami_templated_detector.HttpAction.HttpResponse.BodyH\x00R\bfromBodyB\t\n" +
	"\aextract\x1ae\n" +
	"\n" +
	"ExtractAll\x12W\n" +
	"\bpatterns\x18\x01 \x03(\v2;.tsunami_templated_detector.HttpAction.HttpResponse.ExtractR\bpatterns\x1ae\n" +
	"\n" +
	"ExtractAny\x12W\n" +
	"\bpatterns\x18\x01 \x03(\v2;.tsunami_templated_detector.HttpAction.HttpResponse.ExtractR\bpatterns\x1a\xde\x01\n" +
	"\vExpectation\x12\x1a\n" +
	"\bcontains\x18\x01 \x01(\tR\bcontains\x12T\n" +
	"\x06header\x18\x02 \x01(\v2:.tsunami_templated_detector.HttpAction.HttpResponse.HeaderH\x00R\x06header\x12N\n" +
	"\x04body\x18\x03 \x01(\v28.tsunami_templated_detector.HttpAction.HttpResponse.BodyH\x00R\x04bodyB\r\n" +
	"\vexpectation\x1al\n" +
	"\tExpectAny\x12_\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2?.tsunami_templated_detector.HttpAction.HttpResponse.ExpectationR\n" +
	"conditions\x1al\n" +
	"\tExpectAll\x12_\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2?.tsunami_templated_detector.HttpAction.HttpResponse.ExpectationR\n" +
	"conditionsB\x0e\n" +
	"\fexpectationsB\r\n" +
	"\vextractions\x1a\x88\x01\n" +
	"\x11HttpClientOptions\x128\n" +
	"\x18disable_follow_redirects\x18\x01 \x01(\bR\x16disableFollowRedirects\x129\n" +
	"\x19ignore_http_client_errors\x18\x02 \x01(\bR\x16ignoreHttpClientErrors\"V\n" +
	"\n" +
	"HttpMethod\x12\x16\n" +
	"\x12METHOD_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\b\n" +
	"\x04POST\x10\x02\x12\a\n" +
	"\x03PUT\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x04\x12\b\n" +
	"\x04HEAD\x10\x05B\x9c\x01\n" +
	"(com.google.tsunami.templatedplugin.protoP\x01Zngithub.com/google/tsunami-security-scanner-plugins/templated/templateddetector/proto/templated_plugin_go_protob\x06proto3"

var file_action_http_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_action_http_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_action_http_proto_goTypes = []any{
	(HttpAction_HttpMethod)(0),                  // 0: tsunami_templated_detector.HttpAction.HttpMethod
	(*HttpAction)(nil),                          // 1: tsunami_templated_detector.HttpAction
	(*HttpAction_HttpHeader)(nil),               // 2: tsunami_templated_detector.HttpAction.HttpHeader
	(*HttpAction_HttpResponse)(nil),             // 3: tsunami_templated_detector.HttpAction.HttpResponse
	(*HttpAction_HttpClientOptions)(nil),        // 4: tsunami_templated_detector.HttpAction.HttpClientOptions
	(*HttpAction_HttpResponse_Header)(nil),      // 5: tsunami_templated_detector.HttpAction.HttpResponse.Header
	(*HttpAction_HttpResponse_Body)(nil),        // 6: tsunami_templated_detector.HttpAction.HttpResponse.Body
	(*HttpAction_HttpResponse_Extract)(nil),     // 7: tsunami_templated_detector.HttpAction.HttpResponse.Extract
	(*HttpAction_HttpResponse_ExtractAll)(nil),  // 8: tsunami_templated_detector.HttpAction.HttpResponse.ExtractAll
	(*HttpAction_HttpResponse_ExtractAny)(nil),  // 9: tsunami_templated_detector.HttpAction.HttpResponse.ExtractAny
	(*HttpAction_HttpResponse_Expectation)(nil), // 10: tsunami_templated_detector.HttpAction.HttpResponse.Expectation
	(*HttpAction_HttpResponse_ExpectAny)(nil),   // 11: tsunami_templated_detector.HttpAction.HttpResponse.ExpectAny
	(*HttpAction_HttpResponse_ExpectAll)(nil),   // 12: tsunami_templated_detector.HttpAction.HttpResponse.ExpectAll
}
var file_action_http_proto_depIdxs = []int32{
	0,  // 0: tsunami_templated_detector.HttpAction.method:type_name -> tsunami_templated_detector.HttpAction.HttpMethod
	2,  // 1: tsunami_templated_detector.HttpAction.headers:type_name -> tsunami_templated_detector.HttpAction.HttpHeader
	3,  // 2: tsunami_templated_detector.HttpAction.response:type_name -> tsunami_templated_detector.HttpAction.HttpResponse
	4,  // 3: tsunami_templated_detector.HttpAction.client_options:type_name -> tsunami_templated_detector.HttpAction.HttpClientOptions
	11, // 4: tsunami_templated_detector.HttpAction.HttpResponse.expect_any:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.ExpectAny
	12, // 5: tsunami_templated_detector.HttpAction.HttpResponse.expect_all:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.ExpectAll
	9,  // 6: tsunami_templated_detector.HttpAction.HttpResponse.extract_any:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.ExtractAny
	8,  // 7: tsunami_templated_detector.HttpAction.HttpResponse.extract_all:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.ExtractAll
	5,  // 8: tsunami_templated_detector.HttpAction.HttpResponse.Extract.from_header:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.Header
	6,  // 9: tsunami_templated_detector.HttpAction.HttpResponse.Extract.from_body:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.Body
	7,  // 10: tsunami_templated_detector.HttpAction.HttpResponse.ExtractAll.patterns:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.Extract
	7,  // 11: tsunami_templated_detector.HttpAction.HttpResponse.ExtractAny.patterns:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.Extract
	5,  // 12: tsunami_templated_detector.HttpAction.HttpResponse.Expectation.header:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.Header
	6,  // 13: tsunami_templated_detector.HttpAction.HttpResponse.Expectation.body:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.Body
	10, // 14: tsunami_templated_detector.HttpAction.HttpResponse.ExpectAny.conditions:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.Expectation
	10, // 15: tsunami_templated_detector.HttpAction.HttpResponse.ExpectAll.conditions:type_name -> tsunami_templated_detector.HttpAction.HttpResponse.Expectation
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_action_http_proto_init() }
func file_action_http_proto_init() {
	if File_action_http_proto != nil {
		return
	}
	file_action_http_proto_msgTypes[2].OneofWrappers = []any{
		(*httpAction_HttpResponse_ExpectAny_)(nil),
		(*httpAction_HttpResponse_ExpectAll_)(nil),
		(*httpAction_HttpResponse_ExtractAny_)(nil),
		(*httpAction_HttpResponse_ExtractAll_)(nil),
	}
	file_action_http_proto_msgTypes[6].OneofWrappers = []any{
		(*httpAction_HttpResponse_Extract_FromHeader)(nil),
		(*httpAction_HttpResponse_Extract_FromBody)(nil),
	}
	file_action_http_proto_msgTypes[9].OneofWrappers = []any{
		(*httpAction_HttpResponse_Expectation_Header)(nil),
		(*httpAction_HttpResponse_Expectation_Body)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_http_proto_rawDesc), len(file_action_http_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_http_proto_goTypes,
		DependencyIndexes: file_action_http_proto_depIdxs,
		EnumInfos:         file_action_http_proto_enumTypes,
		MessageInfos:      file_action_http_proto_msgTypes,
	}.Build()
	File_action_http_proto = out.File
	file_action_http_proto_goTypes = nil
	file_action_http_proto_depIdxs = nil
}
