// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: action_utils.proto

package templated_plugin_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SleepUtilityAction struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DurationMs int64                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SleepUtilityAction) Reset() {
	*x = SleepUtilityAction{}
	mi := &file_action_utils_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepUtilityAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepUtilityAction) ProtoMessage() {}

func (x *SleepUtilityAction) ProtoReflect() protoreflect.Message {
	mi := &file_action_utils_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SleepUtilityAction) GetDurationMs() int64 {
	if x != nil {
		return x.xxx_hidden_DurationMs
	}
	return 0
}

func (x *SleepUtilityAction) SetDurationMs(v int64) {
	x.xxx_hidden_DurationMs = v
}

type SleepUtilityAction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The duration of the sleep in milliseconds.
	DurationMs int64
}

func (b0 SleepUtilityAction_builder) Build() *SleepUtilityAction {
	m0 := &SleepUtilityAction{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DurationMs = b.DurationMs
	return m0
}

// Set of utilities that can be used by plugins.
type UtilityAction struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Action isUtilityAction_Action `protobuf_oneof:"action"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UtilityAction) Reset() {
	*x = UtilityAction{}
	mi := &file_action_utils_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtilityAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilityAction) ProtoMessage() {}

func (x *UtilityAction) ProtoReflect() protoreflect.Message {
	mi := &file_action_utils_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UtilityAction) GetSleep() *SleepUtilityAction {
	if x != nil {
		if x, ok := x.xxx_hidden_Action.(*utilityAction_Sleep); ok {
			return x.Sleep
		}
	}
	return nil
}

func (x *UtilityAction) SetSleep(v *SleepUtilityAction) {
	if v == nil {
		x.xxx_hidden_Action = nil
		return
	}
	x.xxx_hidden_Action = &utilityAction_Sleep{v}
}

func (x *UtilityAction) HasAction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Action != nil
}

func (x *UtilityAction) HasSleep() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Action.(*utilityAction_Sleep)
	return ok
}

func (x *UtilityAction) ClearAction() {
	x.xxx_hidden_Action = nil
}

func (x *UtilityAction) ClearSleep() {
	if _, ok := x.xxx_hidden_Action.(*utilityAction_Sleep); ok {
		x.xxx_hidden_Action = nil
	}
}

const UtilityAction_Action_not_set_case case_UtilityAction_Action = 0
const UtilityAction_Sleep_case case_UtilityAction_Action = 1

func (x *UtilityAction) WhichAction() case_UtilityAction_Action {
	if x == nil {
		return UtilityAction_Action_not_set_case
	}
	switch x.xxx_hidden_Action.(type) {
	case *utilityAction_Sleep:
		return UtilityAction_Sleep_case
	default:
		return UtilityAction_Action_not_set_case
	}
}

type UtilityAction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Action:
	Sleep *SleepUtilityAction
	// -- end of xxx_hidden_Action
}

func (b0 UtilityAction_builder) Build() *UtilityAction {
	m0 := &UtilityAction{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Sleep != nil {
		x.xxx_hidden_Action = &utilityAction_Sleep{b.Sleep}
	}
	return m0
}

type case_UtilityAction_Action protoreflect.FieldNumber

func (x case_UtilityAction_Action) String() string {
	md := file_action_utils_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUtilityAction_Action interface {
	isUtilityAction_Action()
}

type utilityAction_Sleep struct {
	Sleep *SleepUtilityAction `protobuf:"bytes,1,opt,name=sleep,proto3,oneof"`
}

func (*utilityAction_Sleep) isUtilityAction_Action() {}

var File_action_utils_proto protoreflect.FileDescriptor

const file_action_utils_proto_rawDesc = "" +
	"\n" +
	"\x12action_utils.proto\x12\x1atsunami_templated_detector\"5\n" +
	"\x12SleepUtilityAction\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMs\"a\n" +
	"\rUtilityAction\x12F\n" +
	"\x05sleep\x18\x01 \x01(\v2..tsunami_templated_detector.SleepUtilityActionH\x00R\x05sleepB\b\n" +
	"\x06actionB\x9c\x01\n" +
	"(com.google.tsunami.templatedplugin.protoP\x01Zngithub.com/google/tsunami-security-scanner-plugins/templated/templateddetector/proto/templated_plugin_go_protob\x06proto3"

var file_action_utils_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_action_utils_proto_goTypes = []any{
	(*SleepUtilityAction)(nil), // 0: tsunami_templated_detector.SleepUtilityAction
	(*UtilityAction)(nil),      // 1: tsunami_templated_detector.UtilityAction
}
var file_action_utils_proto_depIdxs = []int32{
	0, // 0: tsunami_templated_detector.UtilityAction.sleep:type_name -> tsunami_templated_detector.SleepUtilityAction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_action_utils_proto_init() }
func file_action_utils_proto_init() {
	if File_action_utils_proto != nil {
		return
	}
	file_action_utils_proto_msgTypes[1].OneofWrappers = []any{
		(*utilityAction_Sleep)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_utils_proto_rawDesc), len(file_action_utils_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_utils_proto_goTypes,
		DependencyIndexes: file_action_utils_proto_depIdxs,
		MessageInfos:      file_action_utils_proto_msgTypes,
	}.Build()
	File_action_utils_proto = out.File
	file_action_utils_proto_goTypes = nil
	file_action_utils_proto_depIdxs = nil
}
