// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: action_callbackserver.proto

package templated_plugin_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackServerAction_ActionType int32

const (
	CallbackServerAction_ACTION_TYPE_UNSPECIFIED CallbackServerAction_ActionType = 0
	CallbackServerAction_CHECK                   CallbackServerAction_ActionType = 1
)

// Enum value maps for CallbackServerAction_ActionType.
var (
	CallbackServerAction_ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "CHECK",
	}
	CallbackServerAction_ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"CHECK":                   1,
	}
)

func (x CallbackServerAction_ActionType) Enum() *CallbackServerAction_ActionType {
	p := new(CallbackServerAction_ActionType)
	*p = x
	return p
}

func (x CallbackServerAction_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallbackServerAction_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_action_callbackserver_proto_enumTypes[0].Descriptor()
}

func (CallbackServerAction_ActionType) Type() protoreflect.EnumType {
	return &file_action_callbackserver_proto_enumTypes[0]
}

func (x CallbackServerAction_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// CallbackServerAction is used to perform actions that are related to the
// callback server.
type CallbackServerAction struct {
	state                 protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_ActionType CallbackServerAction_ActionType `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=tsunami_templated_detector.CallbackServerAction_ActionType"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CallbackServerAction) Reset() {
	*x = CallbackServerAction{}
	mi := &file_action_callbackserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackServerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackServerAction) ProtoMessage() {}

func (x *CallbackServerAction) ProtoReflect() protoreflect.Message {
	mi := &file_action_callbackserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallbackServerAction) GetActionType() CallbackServerAction_ActionType {
	if x != nil {
		return x.xxx_hidden_ActionType
	}
	return CallbackServerAction_ACTION_TYPE_UNSPECIFIED
}

func (x *CallbackServerAction) SetActionType(v CallbackServerAction_ActionType) {
	x.xxx_hidden_ActionType = v
}

type CallbackServerAction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The action to perform. `CHECK` is probably the most common and is used to
	// check whether the vulnerability was received by the callback server.
	ActionType CallbackServerAction_ActionType
}

func (b0 CallbackServerAction_builder) Build() *CallbackServerAction {
	m0 := &CallbackServerAction{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ActionType = b.ActionType
	return m0
}

var File_action_callbackserver_proto protoreflect.FileDescriptor

const file_action_callbackserver_proto_rawDesc = "" +
	"\n" +
	"\x1baction_callbackserver.proto\x12\x1atsunami_templated_detector\"\xaa\x01\n" +
	"\x14CallbackServerAction\x12\\\n" +
	"\vaction_type\x18\x01 \x01(\x0e2;.tsunami_templated_detector.CallbackServerAction.ActionTypeR\n" +
	"actionType\"4\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05CHECK\x10\x01B\x9c\x01\n" +
	"(com.google.tsunami.templatedplugin.protoP\x01Zngithub.com/google/tsunami-security-scanner-plugins/templated/templateddetector/proto/templated_plugin_go_protob\x06proto3"

var file_action_callbackserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_action_callbackserver_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_action_callbackserver_proto_goTypes = []any{
	(CallbackServerAction_ActionType)(0), // 0: tsunami_templated_detector.CallbackServerAction.ActionType
	(*CallbackServerAction)(nil),         // 1: tsunami_templated_detector.CallbackServerAction
}
var file_action_callbackserver_proto_depIdxs = []int32{
	0, // 0: tsunami_templated_detector.CallbackServerAction.action_type:type_name -> tsunami_templated_detector.CallbackServerAction.ActionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_action_callbackserver_proto_init() }
func file_action_callbackserver_proto_init() {
	if File_action_callbackserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_callbackserver_proto_rawDesc), len(file_action_callbackserver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_callbackserver_proto_goTypes,
		DependencyIndexes: file_action_callbackserver_proto_depIdxs,
		EnumInfos:         file_action_callbackserver_proto_enumTypes,
		MessageInfos:      file_action_callbackserver_proto_msgTypes,
	}.Build()
	File_action_callbackserver_proto = out.File
	file_action_callbackserver_proto_goTypes = nil
	file_action_callbackserver_proto_depIdxs = nil
}
