// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: action_callbackserver.proto

package templated_plugin_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackServerAction_ActionType int32

const (
	CallbackServerAction_ACTION_TYPE_UNSPECIFIED CallbackServerAction_ActionType = 0
	CallbackServerAction_CHECK                   CallbackServerAction_ActionType = 1
)

// Enum value maps for CallbackServerAction_ActionType.
var (
	CallbackServerAction_ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "CHECK",
	}
	CallbackServerAction_ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"CHECK":                   1,
	}
)

func (x CallbackServerAction_ActionType) Enum() *CallbackServerAction_ActionType {
	p := new(CallbackServerAction_ActionType)
	*p = x
	return p
}

func (x CallbackServerAction_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallbackServerAction_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_action_callbackserver_proto_enumTypes[0].Descriptor()
}

func (CallbackServerAction_ActionType) Type() protoreflect.EnumType {
	return &file_action_callbackserver_proto_enumTypes[0]
}

func (x CallbackServerAction_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallbackServerAction_ActionType.Descriptor instead.
func (CallbackServerAction_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_action_callbackserver_proto_rawDescGZIP(), []int{0, 0}
}

// CallbackServerAction is used to perform actions that are related to the
// callback server.
type CallbackServerAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The action to perform. `CHECK` is probably the most common and is used to
	// check whether the vulnerability was received by the callback server.
	ActionType    CallbackServerAction_ActionType `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=tsunami_templated_detector.CallbackServerAction_ActionType" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackServerAction) Reset() {
	*x = CallbackServerAction{}
	mi := &file_action_callbackserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackServerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackServerAction) ProtoMessage() {}

func (x *CallbackServerAction) ProtoReflect() protoreflect.Message {
	mi := &file_action_callbackserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackServerAction.ProtoReflect.Descriptor instead.
func (*CallbackServerAction) Descriptor() ([]byte, []int) {
	return file_action_callbackserver_proto_rawDescGZIP(), []int{0}
}

func (x *CallbackServerAction) GetActionType() CallbackServerAction_ActionType {
	if x != nil {
		return x.ActionType
	}
	return CallbackServerAction_ACTION_TYPE_UNSPECIFIED
}

var File_action_callbackserver_proto protoreflect.FileDescriptor

var file_action_callbackserver_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x74,
	0x73, 0x75, 0x6e, 0x61, 0x6d, 0x69, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xaa, 0x01, 0x0a, 0x14, 0x43, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x5c, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3b, 0x2e, 0x74, 0x73, 0x75, 0x6e, 0x61, 0x6d,
	0x69, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x34, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x17, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43,
	0x48, 0x45, 0x43, 0x4b, 0x10, 0x01, 0x42, 0x9c, 0x01, 0x0a, 0x28, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x73, 0x75, 0x6e, 0x61, 0x6d, 0x69, 0x2e, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x6e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74, 0x73, 0x75, 0x6e, 0x61, 0x6d, 0x69,
	0x2d, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2d, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x64, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x64, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x67, 0x6f, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_action_callbackserver_proto_rawDescOnce sync.Once
	file_action_callbackserver_proto_rawDescData []byte
)

func file_action_callbackserver_proto_rawDescGZIP() []byte {
	file_action_callbackserver_proto_rawDescOnce.Do(func() {
		file_action_callbackserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_callbackserver_proto_rawDesc), len(file_action_callbackserver_proto_rawDesc)))
	})
	return file_action_callbackserver_proto_rawDescData
}

var file_action_callbackserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_action_callbackserver_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_action_callbackserver_proto_goTypes = []any{
	(CallbackServerAction_ActionType)(0), // 0: tsunami_templated_detector.CallbackServerAction.ActionType
	(*CallbackServerAction)(nil),         // 1: tsunami_templated_detector.CallbackServerAction
}
var file_action_callbackserver_proto_depIdxs = []int32{
	0, // 0: tsunami_templated_detector.CallbackServerAction.action_type:type_name -> tsunami_templated_detector.CallbackServerAction.ActionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_action_callbackserver_proto_init() }
func file_action_callbackserver_proto_init() {
	if File_action_callbackserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_callbackserver_proto_rawDesc), len(file_action_callbackserver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_callbackserver_proto_goTypes,
		DependencyIndexes: file_action_callbackserver_proto_depIdxs,
		EnumInfos:         file_action_callbackserver_proto_enumTypes,
		MessageInfos:      file_action_callbackserver_proto_msgTypes,
	}.Build()
	File_action_callbackserver_proto = out.File
	file_action_callbackserver_proto_goTypes = nil
	file_action_callbackserver_proto_depIdxs = nil
}
