// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mock_http_server_tests.proto

package templated_plugin_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MockHttpServer mocks an HTTP server.
type MockHttpServer struct {
	state                    protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_MockResponses *[]*MockHttpServer_MockResponse `protobuf:"bytes,1,rep,name=mock_responses,json=mockResponses,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MockHttpServer) Reset() {
	*x = MockHttpServer{}
	mi := &file_mock_http_server_tests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockHttpServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockHttpServer) ProtoMessage() {}

func (x *MockHttpServer) ProtoReflect() protoreflect.Message {
	mi := &file_mock_http_server_tests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MockHttpServer) GetMockResponses() []*MockHttpServer_MockResponse {
	if x != nil {
		if x.xxx_hidden_MockResponses != nil {
			return *x.xxx_hidden_MockResponses
		}
	}
	return nil
}

func (x *MockHttpServer) SetMockResponses(v []*MockHttpServer_MockResponse) {
	x.xxx_hidden_MockResponses = &v
}

type MockHttpServer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A set of mock responses to be returned by the mock server. A mock response
	// is a pre-defined HTTP response that is returned by the mock server. It
	// contains a set of conditions based on the received request that can be used
	// to control when the response is returned.
	MockResponses []*MockHttpServer_MockResponse
}

func (b0 MockHttpServer_builder) Build() *MockHttpServer {
	m0 := &MockHttpServer{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MockResponses = &b.MockResponses
	return m0
}

type MockHttpServer_HttpHeader struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name  string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MockHttpServer_HttpHeader) Reset() {
	*x = MockHttpServer_HttpHeader{}
	mi := &file_mock_http_server_tests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockHttpServer_HttpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockHttpServer_HttpHeader) ProtoMessage() {}

func (x *MockHttpServer_HttpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_mock_http_server_tests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MockHttpServer_HttpHeader) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *MockHttpServer_HttpHeader) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *MockHttpServer_HttpHeader) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *MockHttpServer_HttpHeader) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type MockHttpServer_HttpHeader_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name  string
	Value string
}

func (b0 MockHttpServer_HttpHeader_builder) Build() *MockHttpServer_HttpHeader {
	m0 := &MockHttpServer_HttpHeader{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Value = b.Value
	return m0
}

type MockHttpServer_HttpCondition struct {
	state                  protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Headers     *[]*MockHttpServer_HttpHeader `protobuf:"bytes,1,rep,name=headers,proto3"`
	xxx_hidden_BodyContent []string                      `protobuf:"bytes,2,rep,name=body_content,json=bodyContent,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MockHttpServer_HttpCondition) Reset() {
	*x = MockHttpServer_HttpCondition{}
	mi := &file_mock_http_server_tests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockHttpServer_HttpCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockHttpServer_HttpCondition) ProtoMessage() {}

func (x *MockHttpServer_HttpCondition) ProtoReflect() protoreflect.Message {
	mi := &file_mock_http_server_tests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MockHttpServer_HttpCondition) GetHeaders() []*MockHttpServer_HttpHeader {
	if x != nil {
		if x.xxx_hidden_Headers != nil {
			return *x.xxx_hidden_Headers
		}
	}
	return nil
}

func (x *MockHttpServer_HttpCondition) GetBodyContent() []string {
	if x != nil {
		return x.xxx_hidden_BodyContent
	}
	return nil
}

func (x *MockHttpServer_HttpCondition) SetHeaders(v []*MockHttpServer_HttpHeader) {
	x.xxx_hidden_Headers = &v
}

func (x *MockHttpServer_HttpCondition) SetBodyContent(v []string) {
	x.xxx_hidden_BodyContent = v
}

type MockHttpServer_HttpCondition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A list of headers and their expected values that must be present in the
	// request.
	Headers []*MockHttpServer_HttpHeader
	// A list strings that must be present in the request's body.
	BodyContent []string
}

func (b0 MockHttpServer_HttpCondition_builder) Build() *MockHttpServer_HttpCondition {
	m0 := &MockHttpServer_HttpCondition{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Headers = &b.Headers
	x.xxx_hidden_BodyContent = b.BodyContent
	return m0
}

type MockHttpServer_MockResponse struct {
	state                  protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Status      int32                         `protobuf:"varint,1,opt,name=status,proto3"`
	xxx_hidden_Uri         string                        `protobuf:"bytes,2,opt,name=uri,proto3"`
	xxx_hidden_Headers     *[]*MockHttpServer_HttpHeader `protobuf:"bytes,3,rep,name=headers,proto3"`
	xxx_hidden_BodyContent string                        `protobuf:"bytes,4,opt,name=body_content,json=bodyContent,proto3"`
	xxx_hidden_Condition   *MockHttpServer_HttpCondition `protobuf:"bytes,5,opt,name=condition,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MockHttpServer_MockResponse) Reset() {
	*x = MockHttpServer_MockResponse{}
	mi := &file_mock_http_server_tests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockHttpServer_MockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockHttpServer_MockResponse) ProtoMessage() {}

func (x *MockHttpServer_MockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mock_http_server_tests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MockHttpServer_MockResponse) GetStatus() int32 {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return 0
}

func (x *MockHttpServer_MockResponse) GetUri() string {
	if x != nil {
		return x.xxx_hidden_Uri
	}
	return ""
}

func (x *MockHttpServer_MockResponse) GetHeaders() []*MockHttpServer_HttpHeader {
	if x != nil {
		if x.xxx_hidden_Headers != nil {
			return *x.xxx_hidden_Headers
		}
	}
	return nil
}

func (x *MockHttpServer_MockResponse) GetBodyContent() string {
	if x != nil {
		return x.xxx_hidden_BodyContent
	}
	return ""
}

func (x *MockHttpServer_MockResponse) GetCondition() *MockHttpServer_HttpCondition {
	if x != nil {
		return x.xxx_hidden_Condition
	}
	return nil
}

func (x *MockHttpServer_MockResponse) SetStatus(v int32) {
	x.xxx_hidden_Status = v
}

func (x *MockHttpServer_MockResponse) SetUri(v string) {
	x.xxx_hidden_Uri = v
}

func (x *MockHttpServer_MockResponse) SetHeaders(v []*MockHttpServer_HttpHeader) {
	x.xxx_hidden_Headers = &v
}

func (x *MockHttpServer_MockResponse) SetBodyContent(v string) {
	x.xxx_hidden_BodyContent = v
}

func (x *MockHttpServer_MockResponse) SetCondition(v *MockHttpServer_HttpCondition) {
	x.xxx_hidden_Condition = v
}

func (x *MockHttpServer_MockResponse) HasCondition() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Condition != nil
}

func (x *MockHttpServer_MockResponse) ClearCondition() {
	x.xxx_hidden_Condition = nil
}

type MockHttpServer_MockResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The HTTP status code to be returned by the mock server.
	Status int32
	// The URI on which this mock response will be returned.
	// Note that in the context of the mock, it **must** contain all GET
	// parameters. For example, `index.php?foo=bar`.
	// Although the leading slash is optional, it is recommended to include it
	// for clarity.
	Uri string
	// The HTTP headers that the mock response will contain.
	Headers []*MockHttpServer_HttpHeader
	// The body content of the mock response.
	BodyContent string
	// A set of additional conditions on the received request that must be met
	// for this mock response to be sent.
	Condition *MockHttpServer_HttpCondition
}

func (b0 MockHttpServer_MockResponse_builder) Build() *MockHttpServer_MockResponse {
	m0 := &MockHttpServer_MockResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_Uri = b.Uri
	x.xxx_hidden_Headers = &b.Headers
	x.xxx_hidden_BodyContent = b.BodyContent
	x.xxx_hidden_Condition = b.Condition
	return m0
}

var File_mock_http_server_tests_proto protoreflect.FileDescriptor

const file_mock_http_server_tests_proto_rawDesc = "" +
	"\n" +
	"\x1cmock_http_server_tests.proto\x12 tsunami_templated_detector_tests\"\xcd\x04\n" +
	"\x0eMockHttpServer\x12d\n" +
	"\x0emock_responses\x18\x01 \x03(\v2=.tsunami_templated_detector_tests.MockHttpServer.MockResponseR\rmockResponses\x1a6\n" +
	"\n" +
	"HttpHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x1a\x89\x01\n" +
	"\rHttpCondition\x12U\n" +
	"\aheaders\x18\x01 \x03(\v2;.tsunami_templated_detector_tests.MockHttpServer.HttpHeaderR\aheaders\x12!\n" +
	"\fbody_content\x18\x02 \x03(\tR\vbodyContent\x1a\x90\x02\n" +
	"\fMockResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12U\n" +
	"\aheaders\x18\x03 \x03(\v2;.tsunami_templated_detector_tests.MockHttpServer.HttpHeaderR\aheaders\x12!\n" +
	"\fbody_content\x18\x04 \x01(\tR\vbodyContent\x12\\\n" +
	"\tcondition\x18\x05 \x01(\v2>.tsunami_templated_detector_tests.MockHttpServer.HttpConditionR\tconditionB\xa2\x01\n" +
	".com.google.tsunami.templatedplugin.proto.testsP\x01Zngithub.com/google/tsunami-security-scanner-plugins/templated/templateddetector/proto/templated_plugin_go_protob\x06proto3"

var file_mock_http_server_tests_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mock_http_server_tests_proto_goTypes = []any{
	(*MockHttpServer)(nil),               // 0: tsunami_templated_detector_tests.MockHttpServer
	(*MockHttpServer_HttpHeader)(nil),    // 1: tsunami_templated_detector_tests.MockHttpServer.HttpHeader
	(*MockHttpServer_HttpCondition)(nil), // 2: tsunami_templated_detector_tests.MockHttpServer.HttpCondition
	(*MockHttpServer_MockResponse)(nil),  // 3: tsunami_templated_detector_tests.MockHttpServer.MockResponse
}
var file_mock_http_server_tests_proto_depIdxs = []int32{
	3, // 0: tsunami_templated_detector_tests.MockHttpServer.mock_responses:type_name -> tsunami_templated_detector_tests.MockHttpServer.MockResponse
	1, // 1: tsunami_templated_detector_tests.MockHttpServer.HttpCondition.headers:type_name -> tsunami_templated_detector_tests.MockHttpServer.HttpHeader
	1, // 2: tsunami_templated_detector_tests.MockHttpServer.MockResponse.headers:type_name -> tsunami_templated_detector_tests.MockHttpServer.HttpHeader
	2, // 3: tsunami_templated_detector_tests.MockHttpServer.MockResponse.condition:type_name -> tsunami_templated_detector_tests.MockHttpServer.HttpCondition
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mock_http_server_tests_proto_init() }
func file_mock_http_server_tests_proto_init() {
	if File_mock_http_server_tests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mock_http_server_tests_proto_rawDesc), len(file_mock_http_server_tests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mock_http_server_tests_proto_goTypes,
		DependencyIndexes: file_mock_http_server_tests_proto_depIdxs,
		MessageInfos:      file_mock_http_server_tests_proto_msgTypes,
	}.Build()
	File_mock_http_server_tests_proto = out.File
	file_mock_http_server_tests_proto_goTypes = nil
	file_mock_http_server_tests_proto_depIdxs = nil
}
