// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mock_callback_server_tests.proto

package templated_plugin_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MockCallbackServer struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3"`
	xxx_hidden_HasInteraction bool                   `protobuf:"varint,2,opt,name=has_interaction,json=hasInteraction,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MockCallbackServer) Reset() {
	*x = MockCallbackServer{}
	mi := &file_mock_callback_server_tests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockCallbackServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockCallbackServer) ProtoMessage() {}

func (x *MockCallbackServer) ProtoReflect() protoreflect.Message {
	mi := &file_mock_callback_server_tests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MockCallbackServer) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *MockCallbackServer) GetHasInteraction() bool {
	if x != nil {
		return x.xxx_hidden_HasInteraction
	}
	return false
}

func (x *MockCallbackServer) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
}

func (x *MockCallbackServer) SetHasInteraction(v bool) {
	x.xxx_hidden_HasInteraction = v
}

type MockCallbackServer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether the callback server is present in the test.
	Enabled bool
	// Whether the callback server reports an interaction. This usually means
	// that true should return a vulnerability.
	HasInteraction bool
}

func (b0 MockCallbackServer_builder) Build() *MockCallbackServer {
	m0 := &MockCallbackServer{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Enabled = b.Enabled
	x.xxx_hidden_HasInteraction = b.HasInteraction
	return m0
}

var File_mock_callback_server_tests_proto protoreflect.FileDescriptor

const file_mock_callback_server_tests_proto_rawDesc = "" +
	"\n" +
	" mock_callback_server_tests.proto\x12 tsunami_templated_detector_tests\"W\n" +
	"\x12MockCallbackServer\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12'\n" +
	"\x0fhas_interaction\x18\x02 \x01(\bR\x0ehasInteractionB\xa2\x01\n" +
	".com.google.tsunami.templatedplugin.proto.testsP\x01Zngithub.com/google/tsunami-security-scanner-plugins/templated/templateddetector/proto/templated_plugin_go_protob\x06proto3"

var file_mock_callback_server_tests_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mock_callback_server_tests_proto_goTypes = []any{
	(*MockCallbackServer)(nil), // 0: tsunami_templated_detector_tests.MockCallbackServer
}
var file_mock_callback_server_tests_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mock_callback_server_tests_proto_init() }
func file_mock_callback_server_tests_proto_init() {
	if File_mock_callback_server_tests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mock_callback_server_tests_proto_rawDesc), len(file_mock_callback_server_tests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mock_callback_server_tests_proto_goTypes,
		DependencyIndexes: file_mock_callback_server_tests_proto_depIdxs,
		MessageInfos:      file_mock_callback_server_tests_proto_msgTypes,
	}.Build()
	File_mock_callback_server_tests_proto = out.File
	file_mock_callback_server_tests_proto_goTypes = nil
	file_mock_callback_server_tests_proto_depIdxs = nil
}
