// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: templated_plugin_tests.proto

package templated_plugin_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines a set of unit test for a templated plugin.
type TemplatedPluginTests struct {
	state             protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Config *TemplatedPluginTests_Config  `protobuf:"bytes,1,opt,name=config,proto3"`
	xxx_hidden_Tests  *[]*TemplatedPluginTests_Test `protobuf:"bytes,2,rep,name=tests,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TemplatedPluginTests) Reset() {
	*x = TemplatedPluginTests{}
	mi := &file_templated_plugin_tests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplatedPluginTests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatedPluginTests) ProtoMessage() {}

func (x *TemplatedPluginTests) ProtoReflect() protoreflect.Message {
	mi := &file_templated_plugin_tests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TemplatedPluginTests) GetConfig() *TemplatedPluginTests_Config {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *TemplatedPluginTests) GetTests() []*TemplatedPluginTests_Test {
	if x != nil {
		if x.xxx_hidden_Tests != nil {
			return *x.xxx_hidden_Tests
		}
	}
	return nil
}

func (x *TemplatedPluginTests) SetConfig(v *TemplatedPluginTests_Config) {
	x.xxx_hidden_Config = v
}

func (x *TemplatedPluginTests) SetTests(v []*TemplatedPluginTests_Test) {
	x.xxx_hidden_Tests = &v
}

func (x *TemplatedPluginTests) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *TemplatedPluginTests) ClearConfig() {
	x.xxx_hidden_Config = nil
}

type TemplatedPluginTests_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Configuration for this set of unit tests. For example, the name of the
	// plugin being tested.
	Config *TemplatedPluginTests_Config
	// The set of tests to run.
	Tests []*TemplatedPluginTests_Test
}

func (b0 TemplatedPluginTests_builder) Build() *TemplatedPluginTests {
	m0 := &TemplatedPluginTests{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Config = b.Config
	x.xxx_hidden_Tests = &b.Tests
	return m0
}

type TemplatedPluginTests_Config struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TestedPlugin string                 `protobuf:"bytes,1,opt,name=tested_plugin,json=testedPlugin,proto3"`
	xxx_hidden_Disabled     bool                   `protobuf:"varint,2,opt,name=disabled,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TemplatedPluginTests_Config) Reset() {
	*x = TemplatedPluginTests_Config{}
	mi := &file_templated_plugin_tests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplatedPluginTests_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatedPluginTests_Config) ProtoMessage() {}

func (x *TemplatedPluginTests_Config) ProtoReflect() protoreflect.Message {
	mi := &file_templated_plugin_tests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TemplatedPluginTests_Config) GetTestedPlugin() string {
	if x != nil {
		return x.xxx_hidden_TestedPlugin
	}
	return ""
}

func (x *TemplatedPluginTests_Config) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *TemplatedPluginTests_Config) SetTestedPlugin(v string) {
	x.xxx_hidden_TestedPlugin = v
}

func (x *TemplatedPluginTests_Config) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
}

type TemplatedPluginTests_Config_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The reference to the name of the tested plugin. This will be used by the
	// engine to create the tests with the correct plugin.
	TestedPlugin string
	// Whether the test should be disabled.
	Disabled bool
}

func (b0 TemplatedPluginTests_Config_builder) Build() *TemplatedPluginTests_Config {
	m0 := &TemplatedPluginTests_Config{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TestedPlugin = b.TestedPlugin
	x.xxx_hidden_Disabled = b.Disabled
	return m0
}

type TemplatedPluginTests_Test struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name                string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_ExpectVulnerability bool                   `protobuf:"varint,2,opt,name=expect_vulnerability,json=expectVulnerability,proto3"`
	xxx_hidden_MockCallbackServer  *MockCallbackServer    `protobuf:"bytes,3,opt,name=mock_callback_server,json=mockCallbackServer,proto3"`
	xxx_hidden_MockHttpServer      *MockHttpServer        `protobuf:"bytes,4,opt,name=mock_http_server,json=mockHttpServer,proto3"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *TemplatedPluginTests_Test) Reset() {
	*x = TemplatedPluginTests_Test{}
	mi := &file_templated_plugin_tests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplatedPluginTests_Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatedPluginTests_Test) ProtoMessage() {}

func (x *TemplatedPluginTests_Test) ProtoReflect() protoreflect.Message {
	mi := &file_templated_plugin_tests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TemplatedPluginTests_Test) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *TemplatedPluginTests_Test) GetExpectVulnerability() bool {
	if x != nil {
		return x.xxx_hidden_ExpectVulnerability
	}
	return false
}

func (x *TemplatedPluginTests_Test) GetMockCallbackServer() *MockCallbackServer {
	if x != nil {
		return x.xxx_hidden_MockCallbackServer
	}
	return nil
}

func (x *TemplatedPluginTests_Test) GetMockHttpServer() *MockHttpServer {
	if x != nil {
		return x.xxx_hidden_MockHttpServer
	}
	return nil
}

func (x *TemplatedPluginTests_Test) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *TemplatedPluginTests_Test) SetExpectVulnerability(v bool) {
	x.xxx_hidden_ExpectVulnerability = v
}

func (x *TemplatedPluginTests_Test) SetMockCallbackServer(v *MockCallbackServer) {
	x.xxx_hidden_MockCallbackServer = v
}

func (x *TemplatedPluginTests_Test) SetMockHttpServer(v *MockHttpServer) {
	x.xxx_hidden_MockHttpServer = v
}

func (x *TemplatedPluginTests_Test) HasMockCallbackServer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MockCallbackServer != nil
}

func (x *TemplatedPluginTests_Test) HasMockHttpServer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MockHttpServer != nil
}

func (x *TemplatedPluginTests_Test) ClearMockCallbackServer() {
	x.xxx_hidden_MockCallbackServer = nil
}

func (x *TemplatedPluginTests_Test) ClearMockHttpServer() {
	x.xxx_hidden_MockHttpServer = nil
}

type TemplatedPluginTests_Test_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of the test.
	Name string
	// Whether this test ensure that the vulnerability is found or not.
	ExpectVulnerability bool
	// Provides a mock for the callback server.
	MockCallbackServer *MockCallbackServer
	// Provides a mock for the HTTP server.
	MockHttpServer *MockHttpServer
}

func (b0 TemplatedPluginTests_Test_builder) Build() *TemplatedPluginTests_Test {
	m0 := &TemplatedPluginTests_Test{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_ExpectVulnerability = b.ExpectVulnerability
	x.xxx_hidden_MockCallbackServer = b.MockCallbackServer
	x.xxx_hidden_MockHttpServer = b.MockHttpServer
	return m0
}

var File_templated_plugin_tests_proto protoreflect.FileDescriptor

const file_templated_plugin_tests_proto_rawDesc = "" +
	"\n" +
	"\x1ctemplated_plugin_tests.proto\x12 tsunami_templated_detector_tests\x1a mock_callback_server_tests.proto\x1a\x1cmock_http_server_tests.proto\"\x9f\x04\n" +
	"\x14TemplatedPluginTests\x12U\n" +
	"\x06config\x18\x01 \x01(\v2=.tsunami_templated_detector_tests.TemplatedPluginTests.ConfigR\x06config\x12Q\n" +
	"\x05tests\x18\x02 \x03(\v2;.tsunami_templated_detector_tests.TemplatedPluginTests.TestR\x05tests\x1aI\n" +
	"\x06Config\x12#\n" +
	"\rtested_plugin\x18\x01 \x01(\tR\ftestedPlugin\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled\x1a\x91\x02\n" +
	"\x04Test\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x14expect_vulnerability\x18\x02 \x01(\bR\x13expectVulnerability\x12f\n" +
	"\x14mock_callback_server\x18\x03 \x01(\v24.tsunami_templated_detector_tests.MockCallbackServerR\x12mockCallbackServer\x12Z\n" +
	"\x10mock_http_server\x18\x04 \x01(\v20.tsunami_templated_detector_tests.MockHttpServerR\x0emockHttpServerB\xa2\x01\n" +
	".com.google.tsunami.templatedplugin.proto.testsP\x01Zngithub.com/google/tsunami-security-scanner-plugins/templated/templateddetector/proto/templated_plugin_go_protob\x06proto3"

var file_templated_plugin_tests_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_templated_plugin_tests_proto_goTypes = []any{
	(*TemplatedPluginTests)(nil),        // 0: tsunami_templated_detector_tests.TemplatedPluginTests
	(*TemplatedPluginTests_Config)(nil), // 1: tsunami_templated_detector_tests.TemplatedPluginTests.Config
	(*TemplatedPluginTests_Test)(nil),   // 2: tsunami_templated_detector_tests.TemplatedPluginTests.Test
	(*MockCallbackServer)(nil),          // 3: tsunami_templated_detector_tests.MockCallbackServer
	(*MockHttpServer)(nil),              // 4: tsunami_templated_detector_tests.MockHttpServer
}
var file_templated_plugin_tests_proto_depIdxs = []int32{
	1, // 0: tsunami_templated_detector_tests.TemplatedPluginTests.config:type_name -> tsunami_templated_detector_tests.TemplatedPluginTests.Config
	2, // 1: tsunami_templated_detector_tests.TemplatedPluginTests.tests:type_name -> tsunami_templated_detector_tests.TemplatedPluginTests.Test
	3, // 2: tsunami_templated_detector_tests.TemplatedPluginTests.Test.mock_callback_server:type_name -> tsunami_templated_detector_tests.MockCallbackServer
	4, // 3: tsunami_templated_detector_tests.TemplatedPluginTests.Test.mock_http_server:type_name -> tsunami_templated_detector_tests.MockHttpServer
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_templated_plugin_tests_proto_init() }
func file_templated_plugin_tests_proto_init() {
	if File_templated_plugin_tests_proto != nil {
		return
	}
	file_mock_callback_server_tests_proto_init()
	file_mock_http_server_tests_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_templated_plugin_tests_proto_rawDesc), len(file_templated_plugin_tests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_templated_plugin_tests_proto_goTypes,
		DependencyIndexes: file_templated_plugin_tests_proto_depIdxs,
		MessageInfos:      file_templated_plugin_tests_proto_msgTypes,
	}.Build()
	File_templated_plugin_tests_proto = out.File
	file_templated_plugin_tests_proto_goTypes = nil
	file_templated_plugin_tests_proto_depIdxs = nil
}
