// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: templated_plugin.proto

package templated_plugin_go_proto

import (
	plugin_representation_go_proto "github.com/google/tsunami-security-scanner/proto/go/plugin_representation_go_proto"
	vulnerability_go_proto "github.com/google/tsunami-security-scanner/proto/go/vulnerability_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginWorkflow_Condition int32

const (
	PluginWorkflow_CONDITION_UNSPECIFIED    PluginWorkflow_Condition = 0
	PluginWorkflow_REQUIRES_CALLBACK_SERVER PluginWorkflow_Condition = 1
)

// Enum value maps for PluginWorkflow_Condition.
var (
	PluginWorkflow_Condition_name = map[int32]string{
		0: "CONDITION_UNSPECIFIED",
		1: "REQUIRES_CALLBACK_SERVER",
	}
	PluginWorkflow_Condition_value = map[string]int32{
		"CONDITION_UNSPECIFIED":    0,
		"REQUIRES_CALLBACK_SERVER": 1,
	}
)

func (x PluginWorkflow_Condition) Enum() *PluginWorkflow_Condition {
	p := new(PluginWorkflow_Condition)
	*p = x
	return p
}

func (x PluginWorkflow_Condition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginWorkflow_Condition) Descriptor() protoreflect.EnumDescriptor {
	return file_templated_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginWorkflow_Condition) Type() protoreflect.EnumType {
	return &file_templated_plugin_proto_enumTypes[0]
}

func (x PluginWorkflow_Condition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ServiceInformation_AuthenticationType int32

const (
	ServiceInformation_AUTHENTICATION_TYPE_UNKNOWN           ServiceInformation_AuthenticationType = 0
	ServiceInformation_AUTHENTICATION_TYPE_USERNAME_PASSWORD ServiceInformation_AuthenticationType = 1
	ServiceInformation_AUTHENTICATION_TYPE_PASSWORD_ONLY     ServiceInformation_AuthenticationType = 2
)

// Enum value maps for ServiceInformation_AuthenticationType.
var (
	ServiceInformation_AuthenticationType_name = map[int32]string{
		0: "AUTHENTICATION_TYPE_UNKNOWN",
		1: "AUTHENTICATION_TYPE_USERNAME_PASSWORD",
		2: "AUTHENTICATION_TYPE_PASSWORD_ONLY",
	}
	ServiceInformation_AuthenticationType_value = map[string]int32{
		"AUTHENTICATION_TYPE_UNKNOWN":           0,
		"AUTHENTICATION_TYPE_USERNAME_PASSWORD": 1,
		"AUTHENTICATION_TYPE_PASSWORD_ONLY":     2,
	}
)

func (x ServiceInformation_AuthenticationType) Enum() *ServiceInformation_AuthenticationType {
	p := new(ServiceInformation_AuthenticationType)
	*p = x
	return p
}

func (x ServiceInformation_AuthenticationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceInformation_AuthenticationType) Descriptor() protoreflect.EnumDescriptor {
	return file_templated_plugin_proto_enumTypes[1].Descriptor()
}

func (ServiceInformation_AuthenticationType) Type() protoreflect.EnumType {
	return &file_templated_plugin_proto_enumTypes[1]
}

func (x ServiceInformation_AuthenticationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// An action is a single unit of work that the plugin can perform. For example
// sending an HTTP request. Each returns a boolean indicating whether the
// action was successful and the last running action defines whether the
// plugin is considered successful (the vulnerability was found).
type PluginAction struct {
	state                     protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Name           string                   `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_CleanupActions []string                 `protobuf:"bytes,2,rep,name=cleanup_actions,json=cleanupActions,proto3"`
	xxx_hidden_AnyAction      isPluginAction_AnyAction `protobuf_oneof:"any_action"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PluginAction) Reset() {
	*x = PluginAction{}
	mi := &file_templated_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginAction) ProtoMessage() {}

func (x *PluginAction) ProtoReflect() protoreflect.Message {
	mi := &file_templated_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginAction) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *PluginAction) GetCleanupActions() []string {
	if x != nil {
		return x.xxx_hidden_CleanupActions
	}
	return nil
}

func (x *PluginAction) GetHttpRequest() *HttpAction {
	if x != nil {
		if x, ok := x.xxx_hidden_AnyAction.(*pluginAction_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *PluginAction) GetCallbackServer() *CallbackServerAction {
	if x != nil {
		if x, ok := x.xxx_hidden_AnyAction.(*pluginAction_CallbackServer); ok {
			return x.CallbackServer
		}
	}
	return nil
}

func (x *PluginAction) GetUtility() *UtilityAction {
	if x != nil {
		if x, ok := x.xxx_hidden_AnyAction.(*pluginAction_Utility); ok {
			return x.Utility
		}
	}
	return nil
}

func (x *PluginAction) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *PluginAction) SetCleanupActions(v []string) {
	x.xxx_hidden_CleanupActions = v
}

func (x *PluginAction) SetHttpRequest(v *HttpAction) {
	if v == nil {
		x.xxx_hidden_AnyAction = nil
		return
	}
	x.xxx_hidden_AnyAction = &pluginAction_HttpRequest{v}
}

func (x *PluginAction) SetCallbackServer(v *CallbackServerAction) {
	if v == nil {
		x.xxx_hidden_AnyAction = nil
		return
	}
	x.xxx_hidden_AnyAction = &pluginAction_CallbackServer{v}
}

func (x *PluginAction) SetUtility(v *UtilityAction) {
	if v == nil {
		x.xxx_hidden_AnyAction = nil
		return
	}
	x.xxx_hidden_AnyAction = &pluginAction_Utility{v}
}

func (x *PluginAction) HasAnyAction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AnyAction != nil
}

func (x *PluginAction) HasHttpRequest() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AnyAction.(*pluginAction_HttpRequest)
	return ok
}

func (x *PluginAction) HasCallbackServer() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AnyAction.(*pluginAction_CallbackServer)
	return ok
}

func (x *PluginAction) HasUtility() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AnyAction.(*pluginAction_Utility)
	return ok
}

func (x *PluginAction) ClearAnyAction() {
	x.xxx_hidden_AnyAction = nil
}

func (x *PluginAction) ClearHttpRequest() {
	if _, ok := x.xxx_hidden_AnyAction.(*pluginAction_HttpRequest); ok {
		x.xxx_hidden_AnyAction = nil
	}
}

func (x *PluginAction) ClearCallbackServer() {
	if _, ok := x.xxx_hidden_AnyAction.(*pluginAction_CallbackServer); ok {
		x.xxx_hidden_AnyAction = nil
	}
}

func (x *PluginAction) ClearUtility() {
	if _, ok := x.xxx_hidden_AnyAction.(*pluginAction_Utility); ok {
		x.xxx_hidden_AnyAction = nil
	}
}

const PluginAction_AnyAction_not_set_case case_PluginAction_AnyAction = 0
const PluginAction_HttpRequest_case case_PluginAction_AnyAction = 3
const PluginAction_CallbackServer_case case_PluginAction_AnyAction = 4
const PluginAction_Utility_case case_PluginAction_AnyAction = 5

func (x *PluginAction) WhichAnyAction() case_PluginAction_AnyAction {
	if x == nil {
		return PluginAction_AnyAction_not_set_case
	}
	switch x.xxx_hidden_AnyAction.(type) {
	case *pluginAction_HttpRequest:
		return PluginAction_HttpRequest_case
	case *pluginAction_CallbackServer:
		return PluginAction_CallbackServer_case
	case *pluginAction_Utility:
		return PluginAction_Utility_case
	default:
		return PluginAction_AnyAction_not_set_case
	}
}

type PluginAction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Each action must have a unique name that will be referenced in the
	// workflows. It must be named using the `[a-zA-Z0-9_]` character set.
	Name string
	// A set of cleanup action to be executed if this action is successful.
	// Once the current action succeed, the cleanups are registered and will
	// always be executed after the last workflow action, whether it is successful
	// or not.
	CleanupActions []string
	// Each action can have one of the following types.

	// Fields of oneof xxx_hidden_AnyAction:
	HttpRequest    *HttpAction
	CallbackServer *CallbackServerAction
	Utility        *UtilityAction
	// -- end of xxx_hidden_AnyAction
}

func (b0 PluginAction_builder) Build() *PluginAction {
	m0 := &PluginAction{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_CleanupActions = b.CleanupActions
	if b.HttpRequest != nil {
		x.xxx_hidden_AnyAction = &pluginAction_HttpRequest{b.HttpRequest}
	}
	if b.CallbackServer != nil {
		x.xxx_hidden_AnyAction = &pluginAction_CallbackServer{b.CallbackServer}
	}
	if b.Utility != nil {
		x.xxx_hidden_AnyAction = &pluginAction_Utility{b.Utility}
	}
	return m0
}

type case_PluginAction_AnyAction protoreflect.FieldNumber

func (x case_PluginAction_AnyAction) String() string {
	md := file_templated_plugin_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPluginAction_AnyAction interface {
	isPluginAction_AnyAction()
}

type pluginAction_HttpRequest struct {
	HttpRequest *HttpAction `protobuf:"bytes,3,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type pluginAction_CallbackServer struct {
	CallbackServer *CallbackServerAction `protobuf:"bytes,4,opt,name=callback_server,json=callbackServer,proto3,oneof"`
}

type pluginAction_Utility struct {
	Utility *UtilityAction `protobuf:"bytes,5,opt,name=utility,proto3,oneof"`
}

func (*pluginAction_HttpRequest) isPluginAction_AnyAction() {}

func (*pluginAction_CallbackServer) isPluginAction_AnyAction() {}

func (*pluginAction_Utility) isPluginAction_AnyAction() {}

// A workflow is a sequence of actions taken in linear order. Having different
// workflows allows the plugin to cover different scenarios based on the
// current Tsunami runtime, for example if the callback server is running.
// Workflows should be defined in order of priority, the first matching workflow
// will be the one selected for running.
type PluginWorkflow struct {
	state                protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Condition PluginWorkflow_Condition    `protobuf:"varint,1,opt,name=condition,proto3,enum=tsunami_templated_detector.PluginWorkflow_Condition"`
	xxx_hidden_Variables *[]*PluginWorkflow_Variable `protobuf:"bytes,2,rep,name=variables,proto3"`
	xxx_hidden_Actions   []string                    `protobuf:"bytes,3,rep,name=actions,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PluginWorkflow) Reset() {
	*x = PluginWorkflow{}
	mi := &file_templated_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginWorkflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginWorkflow) ProtoMessage() {}

func (x *PluginWorkflow) ProtoReflect() protoreflect.Message {
	mi := &file_templated_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginWorkflow) GetCondition() PluginWorkflow_Condition {
	if x != nil {
		return x.xxx_hidden_Condition
	}
	return PluginWorkflow_CONDITION_UNSPECIFIED
}

func (x *PluginWorkflow) GetVariables() []*PluginWorkflow_Variable {
	if x != nil {
		if x.xxx_hidden_Variables != nil {
			return *x.xxx_hidden_Variables
		}
	}
	return nil
}

func (x *PluginWorkflow) GetActions() []string {
	if x != nil {
		return x.xxx_hidden_Actions
	}
	return nil
}

func (x *PluginWorkflow) SetCondition(v PluginWorkflow_Condition) {
	x.xxx_hidden_Condition = v
}

func (x *PluginWorkflow) SetVariables(v []*PluginWorkflow_Variable) {
	x.xxx_hidden_Variables = &v
}

func (x *PluginWorkflow) SetActions(v []string) {
	x.xxx_hidden_Actions = v
}

type PluginWorkflow_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The condition that must be met for this workflow to be selected to run.
	Condition PluginWorkflow_Condition
	// Variables defined at the workflow level that will be available to all
	// actions running in this workflow. These variables are reset to the value
	// defined here between each workflow run.
	Variables []*PluginWorkflow_Variable
	// List of actions (by name) to be run in this workflow.
	Actions []string
}

func (b0 PluginWorkflow_builder) Build() *PluginWorkflow {
	m0 := &PluginWorkflow{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Condition = b.Condition
	x.xxx_hidden_Variables = &b.Variables
	x.xxx_hidden_Actions = b.Actions
	return m0
}

// Each plugin can be slightly configured. For example, it can be disabled or
// debug mode can be enabled.
type PluginConfig struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disabled bool                   `protobuf:"varint,1,opt,name=disabled,proto3"`
	xxx_hidden_Debug    bool                   `protobuf:"varint,2,opt,name=debug,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PluginConfig) Reset() {
	*x = PluginConfig{}
	mi := &file_templated_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginConfig) ProtoMessage() {}

func (x *PluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_templated_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginConfig) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *PluginConfig) GetDebug() bool {
	if x != nil {
		return x.xxx_hidden_Debug
	}
	return false
}

func (x *PluginConfig) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
}

func (x *PluginConfig) SetDebug(v bool) {
	x.xxx_hidden_Debug = v
}

type PluginConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether the plugin is to be disabled. By default, plugins are enabled. So
	// we recommend using this option only to explicitly disable a plugin.
	Disabled bool
	// Debug mode enables very verbose logging for the plugin. For example, for
	// HTTP requests, every request and response will be logged.
	Debug bool
}

func (b0 PluginConfig_builder) Build() *PluginConfig {
	m0 := &PluginConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Disabled = b.Disabled
	x.xxx_hidden_Debug = b.Debug
	return m0
}

type Credential struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login    string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_templated_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_templated_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Credential) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *Credential) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *Credential) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *Credential) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type Credential_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The login to use for the authentication (i.e. username or email)
	Login string
	// The password to use for the authentication.
	Password string
}

func (b0 Credential_builder) Build() *Credential {
	m0 := &Credential{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	return m0
}

// Generic information the service being targeted by the plugin. This is mostly
// used to guide our weak credentials brute-forcers.
type ServiceInformation struct {
	state                         protoimpl.MessageState                `protogen:"opaque.v1"`
	xxx_hidden_AuthenticationType ServiceInformation_AuthenticationType `protobuf:"varint,1,opt,name=authentication_type,json=authenticationType,proto3,enum=tsunami_templated_detector.ServiceInformation_AuthenticationType,oneof"`
	xxx_hidden_DefaultCredentials *[]*Credential                        `protobuf:"bytes,2,rep,name=default_credentials,json=defaultCredentials,proto3"`
	xxx_hidden_CommonCredentials  *[]*Credential                        `protobuf:"bytes,3,rep,name=common_credentials,json=commonCredentials,proto3"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ServiceInformation) Reset() {
	*x = ServiceInformation{}
	mi := &file_templated_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInformation) ProtoMessage() {}

func (x *ServiceInformation) ProtoReflect() protoreflect.Message {
	mi := &file_templated_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceInformation) GetAuthenticationType() ServiceInformation_AuthenticationType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_AuthenticationType
		}
	}
	return ServiceInformation_AUTHENTICATION_TYPE_UNKNOWN
}

func (x *ServiceInformation) GetDefaultCredentials() []*Credential {
	if x != nil {
		if x.xxx_hidden_DefaultCredentials != nil {
			return *x.xxx_hidden_DefaultCredentials
		}
	}
	return nil
}

func (x *ServiceInformation) GetCommonCredentials() []*Credential {
	if x != nil {
		if x.xxx_hidden_CommonCredentials != nil {
			return *x.xxx_hidden_CommonCredentials
		}
	}
	return nil
}

func (x *ServiceInformation) SetAuthenticationType(v ServiceInformation_AuthenticationType) {
	x.xxx_hidden_AuthenticationType = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ServiceInformation) SetDefaultCredentials(v []*Credential) {
	x.xxx_hidden_DefaultCredentials = &v
}

func (x *ServiceInformation) SetCommonCredentials(v []*Credential) {
	x.xxx_hidden_CommonCredentials = &v
}

func (x *ServiceInformation) HasAuthenticationType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ServiceInformation) ClearAuthenticationType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AuthenticationType = ServiceInformation_AUTHENTICATION_TYPE_UNKNOWN
}

type ServiceInformation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// What type of authentication does the service use? (e.g. username and
	// password, password only, etc.)
	AuthenticationType *ServiceInformation_AuthenticationType
	// A list of default known credentials for that service, if available.
	DefaultCredentials []*Credential
	// A list of known common credentials for that service, if available. These
	// are not defaults but are known to often be configured from online
	// playbooks, forums, etc...
	CommonCredentials []*Credential
}

func (b0 ServiceInformation_builder) Build() *ServiceInformation {
	m0 := &ServiceInformation{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AuthenticationType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_AuthenticationType = *b.AuthenticationType
	}
	x.xxx_hidden_DefaultCredentials = &b.DefaultCredentials
	x.xxx_hidden_CommonCredentials = &b.CommonCredentials
	return m0
}

type TemplatedPlugin struct {
	state                         protoimpl.MessageState                     `protogen:"opaque.v1"`
	xxx_hidden_Info               *plugin_representation_go_proto.PluginInfo `protobuf:"bytes,1,opt,name=info,proto3"`
	xxx_hidden_Finding            *vulnerability_go_proto.Vulnerability      `protobuf:"bytes,2,opt,name=finding,proto3"`
	xxx_hidden_Config             *PluginConfig                              `protobuf:"bytes,3,opt,name=config,proto3"`
	xxx_hidden_Actions            *[]*PluginAction                           `protobuf:"bytes,4,rep,name=actions,proto3"`
	xxx_hidden_Workflows          *[]*PluginWorkflow                         `protobuf:"bytes,5,rep,name=workflows,proto3"`
	xxx_hidden_ServiceInformation *ServiceInformation                        `protobuf:"bytes,6,opt,name=service_information,json=serviceInformation,proto3"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *TemplatedPlugin) Reset() {
	*x = TemplatedPlugin{}
	mi := &file_templated_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplatedPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatedPlugin) ProtoMessage() {}

func (x *TemplatedPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_templated_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TemplatedPlugin) GetInfo() *plugin_representation_go_proto.PluginInfo {
	if x != nil {
		return x.xxx_hidden_Info
	}
	return nil
}

func (x *TemplatedPlugin) GetFinding() *vulnerability_go_proto.Vulnerability {
	if x != nil {
		return x.xxx_hidden_Finding
	}
	return nil
}

func (x *TemplatedPlugin) GetConfig() *PluginConfig {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *TemplatedPlugin) GetActions() []*PluginAction {
	if x != nil {
		if x.xxx_hidden_Actions != nil {
			return *x.xxx_hidden_Actions
		}
	}
	return nil
}

func (x *TemplatedPlugin) GetWorkflows() []*PluginWorkflow {
	if x != nil {
		if x.xxx_hidden_Workflows != nil {
			return *x.xxx_hidden_Workflows
		}
	}
	return nil
}

func (x *TemplatedPlugin) GetServiceInformation() *ServiceInformation {
	if x != nil {
		return x.xxx_hidden_ServiceInformation
	}
	return nil
}

func (x *TemplatedPlugin) SetInfo(v *plugin_representation_go_proto.PluginInfo) {
	x.xxx_hidden_Info = v
}

func (x *TemplatedPlugin) SetFinding(v *vulnerability_go_proto.Vulnerability) {
	x.xxx_hidden_Finding = v
}

func (x *TemplatedPlugin) SetConfig(v *PluginConfig) {
	x.xxx_hidden_Config = v
}

func (x *TemplatedPlugin) SetActions(v []*PluginAction) {
	x.xxx_hidden_Actions = &v
}

func (x *TemplatedPlugin) SetWorkflows(v []*PluginWorkflow) {
	x.xxx_hidden_Workflows = &v
}

func (x *TemplatedPlugin) SetServiceInformation(v *ServiceInformation) {
	x.xxx_hidden_ServiceInformation = v
}

func (x *TemplatedPlugin) HasInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Info != nil
}

func (x *TemplatedPlugin) HasFinding() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Finding != nil
}

func (x *TemplatedPlugin) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *TemplatedPlugin) HasServiceInformation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ServiceInformation != nil
}

func (x *TemplatedPlugin) ClearInfo() {
	x.xxx_hidden_Info = nil
}

func (x *TemplatedPlugin) ClearFinding() {
	x.xxx_hidden_Finding = nil
}

func (x *TemplatedPlugin) ClearConfig() {
	x.xxx_hidden_Config = nil
}

func (x *TemplatedPlugin) ClearServiceInformation() {
	x.xxx_hidden_ServiceInformation = nil
}

type TemplatedPlugin_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Plugin metadata, such as its name, author and description.
	Info *plugin_representation_go_proto.PluginInfo
	// Finding that this plugin will report if it finds a vulnerability.
	Finding *vulnerability_go_proto.Vulnerability
	// Plugin-level configuration. For example, to enable debug mode.
	Config *PluginConfig
	// Actions that the plugin can run.
	Actions []*PluginAction
	// Workflows that the plugin can run.
	Workflows []*PluginWorkflow
	// Information about the service that this plugin targets.
	ServiceInformation *ServiceInformation
}

func (b0 TemplatedPlugin_builder) Build() *TemplatedPlugin {
	m0 := &TemplatedPlugin{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Info = b.Info
	x.xxx_hidden_Finding = b.Finding
	x.xxx_hidden_Config = b.Config
	x.xxx_hidden_Actions = &b.Actions
	x.xxx_hidden_Workflows = &b.Workflows
	x.xxx_hidden_ServiceInformation = b.ServiceInformation
	return m0
}

type PluginWorkflow_Variable struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name  string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PluginWorkflow_Variable) Reset() {
	*x = PluginWorkflow_Variable{}
	mi := &file_templated_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginWorkflow_Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginWorkflow_Variable) ProtoMessage() {}

func (x *PluginWorkflow_Variable) ProtoReflect() protoreflect.Message {
	mi := &file_templated_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginWorkflow_Variable) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *PluginWorkflow_Variable) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *PluginWorkflow_Variable) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *PluginWorkflow_Variable) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type PluginWorkflow_Variable_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name  string
	Value string
}

func (b0 PluginWorkflow_Variable_builder) Build() *PluginWorkflow_Variable {
	m0 := &PluginWorkflow_Variable{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Value = b.Value
	return m0
}

var File_templated_plugin_proto protoreflect.FileDescriptor

const file_templated_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16templated_plugin.proto\x12\x1atsunami_templated_detector\x1a\x1bplugin_representation.proto\x1a\x13vulnerability.proto\x1a\x11action_http.proto\x1a\x1baction_callbackserver.proto\x1a\x12action_utils.proto\"\xca\x02\n" +
	"\fPluginAction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fcleanup_actions\x18\x02 \x03(\tR\x0ecleanupActions\x12K\n" +
	"\fhttp_request\x18\x03 \x01(\v2&.tsunami_templated_detector.HttpActionH\x00R\vhttpRequest\x12[\n" +
	"\x0fcallback_server\x18\x04 \x01(\v20.tsunami_templated_detector.CallbackServerActionH\x00R\x0ecallbackServer\x12E\n" +
	"\autility\x18\x05 \x01(\v2).tsunami_templated_detector.UtilityActionH\x00R\autilityB\f\n" +
	"\n" +
	"any_action\"\xcd\x02\n" +
	"\x0ePluginWorkflow\x12R\n" +
	"\tcondition\x18\x01 \x01(\x0e24.tsunami_templated_detector.PluginWorkflow.ConditionR\tcondition\x12Q\n" +
	"\tvariables\x18\x02 \x03(\v23.tsunami_templated_detector.PluginWorkflow.VariableR\tvariables\x12\x18\n" +
	"\aactions\x18\x03 \x03(\tR\aactions\x1a4\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"D\n" +
	"\tCondition\x12\x19\n" +
	"\x15CONDITION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18REQUIRES_CALLBACK_SERVER\x10\x01\"@\n" +
	"\fPluginConfig\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12\x14\n" +
	"\x05debug\x18\x02 \x01(\bR\x05debug\">\n" +
	"\n" +
	"Credential\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xdf\x03\n" +
	"\x12ServiceInformation\x12w\n" +
	"\x13authentication_type\x18\x01 \x01(\x0e2A.tsunami_templated_detector.ServiceInformation.AuthenticationTypeH\x00R\x12authenticationType\x88\x01\x01\x12W\n" +
	"\x13default_credentials\x18\x02 \x03(\v2&.tsunami_templated_detector.CredentialR\x12defaultCredentials\x12U\n" +
	"\x12common_credentials\x18\x03 \x03(\v2&.tsunami_templated_detector.CredentialR\x11commonCredentials\"\x87\x01\n" +
	"\x12AuthenticationType\x12\x1f\n" +
	"\x1bAUTHENTICATION_TYPE_UNKNOWN\x10\x00\x12)\n" +
	"%AUTHENTICATION_TYPE_USERNAME_PASSWORD\x10\x01\x12%\n" +
	"!AUTHENTICATION_TYPE_PASSWORD_ONLY\x10\x02B\x16\n" +
	"\x14_authentication_type\"\xa9\x03\n" +
	"\x0fTemplatedPlugin\x12-\n" +
	"\x04info\x18\x01 \x01(\v2\x19.tsunami.proto.PluginInfoR\x04info\x126\n" +
	"\afinding\x18\x02 \x01(\v2\x1c.tsunami.proto.VulnerabilityR\afinding\x12@\n" +
	"\x06config\x18\x03 \x01(\v2(.tsunami_templated_detector.PluginConfigR\x06config\x12B\n" +
	"\aactions\x18\x04 \x03(\v2(.tsunami_templated_detector.PluginActionR\aactions\x12H\n" +
	"\tworkflows\x18\x05 \x03(\v2*.tsunami_templated_detector.PluginWorkflowR\tworkflows\x12_\n" +
	"\x13service_information\x18\x06 \x01(\v2..tsunami_templated_detector.ServiceInformationR\x12serviceInformationB\x9c\x01\n" +
	"(com.google.tsunami.templatedplugin.protoP\x01Zngithub.com/google/tsunami-security-scanner-plugins/templated/templateddetector/proto/templated_plugin_go_protob\x06proto3"

var file_templated_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_templated_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_templated_plugin_proto_goTypes = []any{
	(PluginWorkflow_Condition)(0),                     // 0: tsunami_templated_detector.PluginWorkflow.Condition
	(ServiceInformation_AuthenticationType)(0),        // 1: tsunami_templated_detector.ServiceInformation.AuthenticationType
	(*PluginAction)(nil),                              // 2: tsunami_templated_detector.PluginAction
	(*PluginWorkflow)(nil),                            // 3: tsunami_templated_detector.PluginWorkflow
	(*PluginConfig)(nil),                              // 4: tsunami_templated_detector.PluginConfig
	(*Credential)(nil),                                // 5: tsunami_templated_detector.Credential
	(*ServiceInformation)(nil),                        // 6: tsunami_templated_detector.ServiceInformation
	(*TemplatedPlugin)(nil),                           // 7: tsunami_templated_detector.TemplatedPlugin
	(*PluginWorkflow_Variable)(nil),                   // 8: tsunami_templated_detector.PluginWorkflow.Variable
	(*HttpAction)(nil),                                // 9: tsunami_templated_detector.HttpAction
	(*CallbackServerAction)(nil),                      // 10: tsunami_templated_detector.CallbackServerAction
	(*UtilityAction)(nil),                             // 11: tsunami_templated_detector.UtilityAction
	(*plugin_representation_go_proto.PluginInfo)(nil), // 12: tsunami.proto.PluginInfo
	(*vulnerability_go_proto.Vulnerability)(nil),      // 13: tsunami.proto.Vulnerability
}
var file_templated_plugin_proto_depIdxs = []int32{
	9,  // 0: tsunami_templated_detector.PluginAction.http_request:type_name -> tsunami_templated_detector.HttpAction
	10, // 1: tsunami_templated_detector.PluginAction.callback_server:type_name -> tsunami_templated_detector.CallbackServerAction
	11, // 2: tsunami_templated_detector.PluginAction.utility:type_name -> tsunami_templated_detector.UtilityAction
	0,  // 3: tsunami_templated_detector.PluginWorkflow.condition:type_name -> tsunami_templated_detector.PluginWorkflow.Condition
	8,  // 4: tsunami_templated_detector.PluginWorkflow.variables:type_name -> tsunami_templated_detector.PluginWorkflow.Variable
	1,  // 5: tsunami_templated_detector.ServiceInformation.authentication_type:type_name -> tsunami_templated_detector.ServiceInformation.AuthenticationType
	5,  // 6: tsunami_templated_detector.ServiceInformation.default_credentials:type_name -> tsunami_templated_detector.Credential
	5,  // 7: tsunami_templated_detector.ServiceInformation.common_credentials:type_name -> tsunami_templated_detector.Credential
	12, // 8: tsunami_templated_detector.TemplatedPlugin.info:type_name -> tsunami.proto.PluginInfo
	13, // 9: tsunami_templated_detector.TemplatedPlugin.finding:type_name -> tsunami.proto.Vulnerability
	4,  // 10: tsunami_templated_detector.TemplatedPlugin.config:type_name -> tsunami_templated_detector.PluginConfig
	2,  // 11: tsunami_templated_detector.TemplatedPlugin.actions:type_name -> tsunami_templated_detector.PluginAction
	3,  // 12: tsunami_templated_detector.TemplatedPlugin.workflows:type_name -> tsunami_templated_detector.PluginWorkflow
	6,  // 13: tsunami_templated_detector.TemplatedPlugin.service_information:type_name -> tsunami_templated_detector.ServiceInformation
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_templated_plugin_proto_init() }
func file_templated_plugin_proto_init() {
	if File_templated_plugin_proto != nil {
		return
	}
	file_action_http_proto_init()
	file_action_callbackserver_proto_init()
	file_action_utils_proto_init()
	file_templated_plugin_proto_msgTypes[0].OneofWrappers = []any{
		(*pluginAction_HttpRequest)(nil),
		(*pluginAction_CallbackServer)(nil),
		(*pluginAction_Utility)(nil),
	}
	file_templated_plugin_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_templated_plugin_proto_rawDesc), len(file_templated_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_templated_plugin_proto_goTypes,
		DependencyIndexes: file_templated_plugin_proto_depIdxs,
		EnumInfos:         file_templated_plugin_proto_enumTypes,
		MessageInfos:      file_templated_plugin_proto_msgTypes,
	}.Build()
	File_templated_plugin_proto = out.File
	file_templated_plugin_proto_goTypes = nil
	file_templated_plugin_proto_depIdxs = nil
}
