# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "Zimbra_CVE_2019_9670"
}

tests: {
  name: "whenOobVulnerable_returnsVuln"
  expect_vulnerability: true

  mock_callback_server: {
    enabled: true
    has_interaction: true
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: 
          '... Zimbra Collaboration Suite Web Client ...'
      },
      {
        uri: "/Autodiscover/Autodiscover.xml"
        status: 503
        body_content: 
          "... error  ..."
      }
    ]
  }
}

tests: {
  name: "whenReflectedVulnerable_returnsVuln"
  expect_vulnerability: true

  mock_callback_server: {
    enabled: false
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: 
          '... Zimbra Collaboration Suite Web Client ...'
      },
      {
        uri: "/Autodiscover/Autodiscover.xml"
        status: 503
        body_content: 
          "... Error 503 Requested response schema not available ... {{ T_UTL_CURRENT_TIMESTAMP_MS }}  ..."
      }
    ]
  }
}

tests: {
  name: "whenOobNotVulnerable_returnsNotVuln"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: true
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: 
          '... Zimbra Collaboration Suite Web Client ...'
      },
      {
        uri: "/Autodiscover/Autodiscover.xml"
        status: 503
        body_content: 
          "... error  ..."
      }
    ]
  }
}

tests: {
  name: "whenRandomServer_returnsFalse"
  expect_vulnerability: false


  mock_http_server: {
    mock_responses: [
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "Hello world"
      }
    ]
  }
}

