version: '3'

services:
  master:
    image: "locustio/locust:${LC_VERSION}"
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    image: "locustio/locust:${LC_VERSION}"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
