# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "H2o_CVE_2023_6018"
}

tests: {
  name: "whenVulnerable_returnsTrue"
  expect_vulnerability: true

  mock_callback_server: {
    enabled: true
    has_interaction: true
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/3/ModelBuilders/generic"
        status: 200
        body_content: "{\"model_id\"=\"irrelevant\"&\"algo_full_name\"=\"Import MOJO Model\"}"
      }
    ]
  }
}

tests: {
  name: "whenNoCallback_returnsFalse"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: true
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/3/ModelBuilders/generic"
        status: 200
        body_content: "{\"model_id\"=\"irrelevant\"&\"algo_full_name\"=\"Import MOJO Model\"}"
      }
    ]
  }
}

tests: {
  name: "whenNotH2o_returnsFalse"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: true
    has_interaction: true
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "Login to your Drupal account"
      }
    ]
  }
}