# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "ApacheLivy_ExposedUI"
}

tests: {
  name: "whenVulnerable_returnsVuln"
  expect_vulnerability: true

  mock_callback_server: {
    enabled: true
    has_interaction: true
  }
  mock_http_server: {
    mock_responses: [
      {
        uri: "/ui"
        status: 200
        body_content: '<title>Livy - Sessions</title>'
      },
      {
        uri: "/batches"
        status: 201
        body_content:
          '{"id":6,"name":null,"owner":null,"proxyUser":null,"state":"running","appId":null,"appInfo":{"driverLogUrl":null,"sparkUiUrl":null},"log":["stdout: ","\nstderr: "]}'
        condition: {
          body_content: '{"file":"{{ T_CBS_URI }}"}'
          headers: [
            {
              name: "Content-Type",
              value: "application/json"
            }
          ]
        }
      },
      {
        uri: "/batches/6"
        status: 200
      }
    ]
  }
}


tests: {
  name: "whenNotApcheLivy_returnsNoVuln"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri:  "/api/v1/main/usages/all"
        status: 400
        body_content: "..."
      }
    ]
  }
}

tests: {
  name: "whenNoCallback_returnsFalse"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: true
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/ui"
        status: 200
        body_content: '<title>Livy - Sessions</title>'
      },
      {
        uri: "/batches"
        status: 201
        body_content:
            '{"id":6,"name":null,"owner":null,"proxyUser":null,"state":"running","appId":null,"appInfo":{"driverLogUrl":null,"sparkUiUrl":null},"log":["stdout: ","\nstderr: "]}'
        condition: {
          body_content: '{"file":"{{ T_CBS_URI }}"}'
          headers: [
            {
              name: "Content-Type",
              value: "application/json"
            }
          ]
        }
      },
      {
        uri: "/batches/6"
        status: 200
        body_content:
            '{"id":0,"code":"import subprocess\\nsubprocess.run([\\"wget\\",\\"{{ T_CBS_URI }}\\"])","state":"available","output":{"status":"ok","execution_count":0,"data":{"text/plain":"/opt"}},"progress":1.0,"started":1754515902001,"completed":1754515902003}'
      }
    ]
  }
}