# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "ApacheSpark_ExposedUI"
}

tests: {
  name: "whenVulnerable_returnsVuln"
  expect_vulnerability: true

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content:
          "<title>Spark Worker at 192.168.48.3:36075</title><body><span "
          "class=\"collapse-aggregated-runningExecutors collapse-table\" "
          "onClick=\"collapseTable(\'collapse-aggregated-runningExecutors\',\n"
          "\'aggregated-runningExecutors\')\"></body>"
      }
    ]
  }
}

tests: {
  name: "whenNotApacheSpark_returnsNoVuln"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: "random response"
      }
    ]
  }
}

tests: {
  name: "whenNotVulnerable_returnsNoVuln"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 403
      }
    ]
  }
}

