# proto-file: proto/templated_plugin.proto
# proto-message: TemplatedPlugin

###############
# PLUGIN INFO #
###############

info: {
  type: VULN_DETECTION
  name: "ApacheSpark_ExposedUI"
  author: "Timo Mueller (work@mtimo.de)"
  version: "0.1"
}

finding: {
  main_id: {
    publisher: "TSUNAMI_COMMUNITY"
    value: "Apache_Spark_Exposed_WebUI"
  }
  title:
    "Exposed Apache Spark UI which discloses information about the Apache "
    "Spark environment and its' tasks."
  description:
    "An exposed Apache Spark Web UI provides attackers information about the "
    "Apache Spark UI and its' tasks. The disclosed information might leak "
    "other configured Apache Spark nodes and the output of previously run "
    "tasks. Depending on the task, the output might contain sensitive "
    "information which was logged during the task execution."
  recommendation: "Don't expose the Apache Spark Web UI to unauthenticated attackers."
  severity: MEDIUM
}

###########
# ACTIONS #
###########

actions: {
  name: "is_apache_spark"
  http_request: {
    method: GET
    uri: "/"
    response: {
      http_status: 200
      expect_all: {
        conditions: { body: {} contains: "<title>Spark " }
        conditions: { body: {} contains: "onClick=\"collapseTable(\'collapse-aggregated-" }
      }
    }
  }
}

#############
# WORKFLOWS #
#############

workflows: {
  actions: [
    "is_apache_spark"
  ]
}
