# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "ApachePinot_ExposedUI"
}

tests: {
  name: "whenVulnerable_returnsTrue"
  expect_vulnerability: true

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: "<!DOCTYPE html><html><header><meta name=\"description\" content=\"Pinot Controller UI\"></header></html>"
      },
      {
        uri: "/tables"
        status: 200
        body_content: "{\"tables\":[\"airlineStats\",\"baseballStats\"]"
      }
    ]
  }
}

tests: {
  name: "whenNotApachePinot_returnsFalse"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "Hello world"
      }
    ]
  }
}
