# proto-file: proto/templated_plugin.proto
# proto-message: TemplatedPlugin

###############
# PLUGIN INFO #
###############

info: {
  type: VULN_DETECTION
  name: "ApacheLivy_ExposedUI"
  author: "joernNNN"
  version: "0.1"
}

finding: {
  main_id: {
    publisher: "GOOGLE"
    value: "APACHELIVY_EXPOSED_UI"
  }
  title: "Apache Livy Exposed instance"
  description: "Apache Livy instance is exposed and can be used to compromise the system."
  recommendation:
    "Configure authentication or ensure the Apache Livy instance is not exposed "
    "to the network. See "
    "https://livy.apache.org/get-started/ for details."
  severity: CRITICAL
}

###########
# ACTIONS #
###########

actions: {
  name: "livy_exposed_ui_fingerprint"
  http_request: {
    method: GET
    uri: "/ui"
    response: {
      http_status: 200
      expect_all: {
        conditions: { body {} contains: '<title>Livy - Sessions</title>' }
      }
    }
  }
}

actions: {
  name: "create_batches"
  http_request: {
    method: POST
    uri: "/batches"
    headers: [
      { name: "Content-Type" value: "application/json" }
    ]
    data: '{"file":"{{ T_CBS_URI }}"}'
    response: {
      http_status: 201
      expect_all: {
        conditions: { body {} contains: '"proxyUser"' }
        conditions: { body {} contains: '"sparkUiUrl"' }
      }
      extract_all: {
        patterns: [
          {
            from_body: {}
            regexp: "\"id\":([0-9]+),"
            variable_name: "batch_id"
          }
        ]
      }
    }
  }
  cleanup_actions: "cleanup_batches"
}

actions: {
  name: "cleanup_batches"
  http_request: {
    method: DELETE
    uri: "/batches/{{ batch_id }}"
    response: {
      http_status: 200
    }
  }
}

actions: {
  name: "sleep_for_callback"
  utility: { sleep: { duration_ms: 4000 } }
}
actions: {
  name: "check_callback_server_logs"
  callback_server: { action_type: CHECK }
}

config:{
  debug: true
}
#############
# WORKFLOWS #
#############

workflows: {
  actions: [
    "livy_exposed_ui_fingerprint",
    "create_batches",
    "sleep_for_callback",
    "check_callback_server_logs"
  ]
}