# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "Ollama_ExposedUI"
}

tests: {
  name: "whenUIandAPI_returnsVuln"
  expect_vulnerability: true

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: "Ollama is running"
      },
      {
        uri: "/api/ps"
        status: 200
        body_content: "{\"models\":"
      },
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: '{"status":200}'
      }
    ]
  }
}

tests: {
  name: "whenNoApi_returnsNotVuln"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: "Ollama is running"
      },
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: '{"status":200}'
      }
    ]
  }
}

tests: {
  name: "whenNoUI_returnsNotVuln"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri: "/api/ps"
        status: 200
        body_content: "{\"models\":"
      },
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: '{"status":200}'
      }
    ]
  }
}


tests: {
  name: "whenRandomServer_returnsNotVuln"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri:  "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "... Hello world ..."
      }
    ]
  }
}
