# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "SeleniumGrid_ExposedUI"
}

tests: {
  name: "whenOobVulnerable_returnsTrue"
  expect_vulnerability: true

  mock_callback_server: {
    enabled: true
    has_interaction: true
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/status"
        status: 200
        body_content: 
          '{'
          '  "value": {'
          '    "ready": true,'
          '    "message": "Selenium Grid ready.",'
          '    ...'
          '  }'
          '}'
      },
      {
        uri: "/wd/hub/session"
        status: 200
        body_content: 
          '{'
          '"value": {'
          '"sessionId": "bbbbb",'
          '}, ...'
          '}'
      },
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: ' ... '
      }
    ]
  }
}

tests: {
  name: "whenOobNotVulnerable_returnsFalse"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: true
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/status"
        status: 200
        body_content: 
          '{'
          '  "value": {'
          '    "ready": true,'
          '    "message": "Selenium Grid ready.",'
          '    ...'
          '  }'
          '}'
      },
      {
        uri: "/wd/hub/session"
        status: 200
        body_content: 
          '{'
          '"value": {'
          '"sessionId": "bbbbb",'
          '}, ...'
          '}'
      },
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: ' ... '
      }
    ]
  }
}

tests: {
  name: "whenRandomServer_returnsFalse"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: true
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "Login to your Drupal account"
      }
    ]
  }
}
