# proto-file: proto/templated_plugin.proto
# proto-message: TemplatedPlugin

###############
# PLUGIN INFO #
###############

info: {
  type: VULN_DETECTION
  name: "Wordpress_UnfinishedInstall_ExposedUI"
  author: 
    "Robert Dick (robert@doyensec.com) for templated version, "
    "Tsunami Team (tsunami-dev@google.com) for original Java version"
  version: "1.0"
}

finding: {
  main_id: {
    publisher: "GOOGLE"
    value: "UNFINISHED_WORD_PRESS_INSTALLATION"
  }
  severity: CRITICAL
  title: "Unfinished WordPress Installation"
  description: 
    "An unfinished WordPress installation exposes the /wp-admin/install.php page,"
    " which allows attacker to set the admin password and possibly compromise the system."
  recommendation: "Do not leave this installation page in place. Either finish the installation or remove Wordpress."
}

config: {}

###########
# ACTIONS #
###########

actions: {
  name: "fingerprint_wordpress_install"
  http_request: {
    method: GET
    uri: "/wp-admin/install.php?step=1"
    response: {
      http_status: 200
      expect_all: {
        conditions: [
          { body: {} contains: 'WordPress' },
          { body: {} contains: '<form id="setup"' }
        ]
      }
    }
  }
}

#############
# WORKFLOWS #
#############

workflows: {
  actions: [
    "fingerprint_wordpress_install"
  ]
}
