version: '3'
services:
  solr:
    image: solr:${SOLR_VERSION}
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
volumes:
  data:
