# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "KafkaUi_CVE_2023_52251"
}

tests: {
  name: "whenVulnerableKafkaUi_returnsTrue"
  expect_vulnerability: true

  mock_callback_server: {
    enabled: true
    has_interaction: true
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/does-not-exist"
        status: 404,
        body_content: "org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND , com.provectus.kafka.ui.config , com.provectus.kafka.ui.config.ReadOnlyModeFilter"
      },
      {
        uri: "/api/clusters/local/topics"
        status: 200,
        body_content: "{\"name\":\"tsunami-security-scanner\",\"internal\":false,\"partitionCount\":1,\"replicationFactor\":1,"
      },
      {
        uri: "/api/clusters/local/topics/tsunami-security-scanner/messages"
        status: 200
      },
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
      },
      {
        uri: "/api/clusters/local/topics/tsunami-security-scanner"
        status: 200
      }
    ]
  }
}

tests: {
  name: "whenNotKafkaUi_returnsNoVuln"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri: "/api/clusters/local/topics"
        status: 200
      },
      {
        uri: "/api/clusters/local/topics/topic/messages"
        status: 200
      }
    ]
  }
}