# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "ApacheOfbiz_CVE_2024_32113"
}

tests: {
  name: "whenOobVulnerable_returnsVuln"
  expect_vulnerability: true

  mock_callback_server: {
    enabled: true
    has_interaction: true
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/webtools/control/forgotPassword/foo/../ProgramExport"
        status: 200
        body_content: 
          '...'
      },
      {
        uri: "/"
        status: 200
        body_content: 
          '...'
      }
    ]
  }
}


tests: {
  name: "whenOobNotVulnerable_returnsNotVuln"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: true
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/webtools/control/forgotPassword/foo/../ProgramExport"
        status: 200
        body_content: 
          '...'
      },
      {
        uri: "/"
        status: 200
        body_content: 
          '...'
      }
    ]
  }
}

tests: {
  name: "whenRandomServer_returnsFalse"
  expect_vulnerability: false


  mock_http_server: {
    mock_responses: [
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "Hello world"
      }
    ]
  }
}

