# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "LlamaFactory_CVE_2024_52803"
  disabled: false
}

tests: {
  name: "whenVulnerable_returnsTrue"
  expect_vulnerability: true

  mock_callback_server: {
    enabled: true
    has_interaction: true
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: "<html><meta property=\"og:title\" content=\"LLaMA Board\" /><script>window.gradio_config = {};</script></html>"
      },
      {
        uri: "/queue/join"
        status: 200
        body_content: "{\"event_id\":\"abc123def456\"}"
      },
      {
        uri: "/queue/data?session_hash=tsunami{{ T_UTL_CURRENT_TIMESTAMP_MS }}"
        status: 200
        body_content: "data: {\"msg\":\"process_completed\",\"output\":{\"data\":[\"Failed.\"],\"error\":\"\"},\"success\":true}\n\n"
      }
    ]
  }
}

tests: {
  name: "whenNoCallback_returnsFalse"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: true
    has_interaction: false
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 200
        body_content: "<html><meta property=\"og:title\" content=\"LLaMA Board\" /><script>window.gradio_config = {};</script></html>"
      },
      {
        uri: "/queue/join"
        status: 200
        body_content: "{\"event_id\":\"abc123def456\"}"
      },
      {
        uri: "/queue/data?session_hash=tsunami{{ T_UTL_CURRENT_TIMESTAMP_MS }}"
        status: 200
        body_content: "data: {\"msg\":\"process_completed\",\"output\":{\"data\":[\"Failed.\"],\"error\":\"\"},\"success\":true}\n\n"
      }
    ]
  }
}

tests: {
  name: "whenNotLlamaFactory_returnsFalse"
  expect_vulnerability: false

  mock_callback_server: {
    enabled: true
    has_interaction: true
  }

  mock_http_server: {
    mock_responses: [
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "Login to your WordPress account"
      }
    ]
  }
}
