# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "LlamaFactory_CVE_2024_52803"
  disabled: false
}

tests: {
  name: "whenVulnerable_returnsTrue"
  expect_vulnerability: true

  mock_http_server: {
    mock_responses: [
      {
        uri: "/queue/join"
        status: 200
        body_content: "{\"event_id\":\"abc123def456\"}"
      },
      {
        uri: "/queue/data?session_hash=tsunami{{ T_UTL_CURRENT_TIMESTAMP_MS }}"
        status: 200
        body_content: "data: {\"msg\":\"process_completed\",\"output\":{\"data\":[\"tsunami1350\"],\"error\":\"\"},\"success\":true}\n\n"
      }
    ]
  }
}

tests: {
  name: "whenNotVulnerable_returnsFalse"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri: "/queue/join"
        status: 200
        body_content: "{\"event_id\":\"abc123def456\"}"
      },
      {
        uri: "/queue/data?session_hash=tsunami{{ T_UTL_CURRENT_TIMESTAMP_MS }}"
        status: 200
        body_content: "data: {\"msg\":\"process_completed\",\"output\":{\"data\":[\"Output\"],\"error\":\"Command not executed\"},\"success\":false}\n\n"
      }
    ]
  }
}

tests: {
  name: "whenNotLlamaFactory_returnsFalse"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "Login to your WordPress account"
      }
    ]
  }
}
