services:
  grafana:
    image: "grafana/grafana:${GRAFANA_VERSION}"
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}
