name: doyensec-plugins-build

on:
  pull_request:
    paths:
      - 'doyensec/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: google/tsunami-plugins-doyensec
  PLUGINS_CATEGORY: doyensec
  PLUGINS_FOLDER: doyensec

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "TSUNAMI_PLUGIN_FOLDER=${{ env.PLUGINS_FOLDER }}"
